### ISSUE TITLE
[BUG] CAU cannot live migrate AKS control plane VM's without processor compatibility set

### ISSUE THREAD

**Issue by bcosden** [Azure/aks-hci#101]
**Describe the bug**
When a cluster has CPU's from the same family but not identical chips, Hyper-V takes advantage of features of that chip that does not allow for the roles to be drained. Instead a failure occurs and suggests that processor compatibility mode be set for the Hyper-V VM's. However, this cannot be set manually since the cluster is running and the scripts that set-up the cluster do not allow for this flag to be set.

**To Reproduce**
1. Create an AKS cluster using 2 nodes with Xeon Silver 4110 and Xeon Silver 4210
2. Use cluster aware updating tool or WAC. When an update is installed that requires a server reboot, the roles are drained.
3. However, draining will fail and the restart prevented.

**Expected behavior**
Allow the user to set the processor compatibility mode in WAC and the Powershell scripts for installing an AKS cluster.

**Environment (please complete the following information):**
- OS: Azure Stack HCI latest version
- AKS-HCI Version 1.0.0
- Kubernetes Version (i.e. 1.19.7)

**Additional context**
This is a blocking issue. Since I cannot upgrade my cluster successfully and I cannot apply the compatibility flag without destroying the cluster or putting the cluster in an invalid state, there is no way to run AKS HCI without the ability to run server updates.

**Comment by mkostersitz** [comment]
On Azure Stack HCI GA release marking VMs as compatible if they are not, could lead to performance degradation. The behavior of the underlying HCI platform has been improved in the next version of Azure Stack HCI. AKS-HCI takes advantage of these improvements. We will not backport the issue to Azure Stack HCI GA release because of complex interdependency.
