### ISSUE TITLE
Scale your Kubernetes cluster (Target cluster) - Set-AksHciClusterNodeCount - command not found

### ISSUE THREAD

**Issue by SurbhiAgarwal12** [Azure/aks-hci#109]
I am trying to execute the step - Set-AksHciClusterNodeCount –Name akshciclus001 -linuxNodeCount 2 -windowsNodeCount 1
But it is failing with the error - 
[akshcihost001.akshci.local]: PS C:\Users\AzureUser\Documents> Set-AksHciClusterNodeCount -Name my-workload-cluster -linuxNodeCount 2 -windowsNodeCount 1
The term 'Set-AksHciClusterNodeCount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Set-AksHciClusterNodeCount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I am also attaching the output of 
 Import-Module AksHci
 Get-Command -Module AksHci

If you notice there is no such "Set-AksHciClusterNodeCount" module is imported.

Connecting to akshcihost001.akshci.local, Logon user AKSHCIHost001\AzureUser
[akshcihost001.akshci.local]: PS C:\Users\AzureUser\Documents> Import-Module AksHci
>> Get-Command -Module AksHci
>>

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Initialize-AksHciNode                              1.0.2      AksHci
Function        Add-AksHciGMSACredentialSpec                       1.0.2      AksHci
Function        Add-AksHciNode                                     1.0.2      AksHci
Function        Disable-AksHciArcConnection                        1.0.2      AksHci
Function        Enable-AksHciArcConnection                         1.0.2      AksHci
Function        Get-AksHciBillingStatus                            1.0.2      AksHci
Function        Get-AksHciCluster                                  1.0.2      AksHci
Function        Get-AksHciClusterNetwork                           1.0.2      AksHci
Function        Get-AksHciClusterUpdates                           1.0.2      AksHci
Function        Get-AksHciConfig                                   1.0.2      AksHci
Function        Get-AksHciCredential                               1.0.2      AksHci
Function        Get-AksHciEventLog                                 1.0.2      AksHci
Function        Get-AksHciKubernetesVersion                        1.0.2      AksHci
Function        Get-AksHciLogs                                     1.0.2      AksHci
Function        Get-AksHciProxySetting                             1.0.2      AksHci
Function        Get-AksHciRegistration                             1.0.2      AksHci
Function        Get-AksHciStorageContainer                         1.0.2      AksHci
Function        Get-AksHciUpdates                                  1.0.2      AksHci
Function        Get-AksHciVersion                                  1.0.2      AksHci
Function        Get-AksHciVmSize                                   1.0.2      AksHci
Function        Install-AksHci                                     1.0.2      AksHci
Function        Install-AksHciAdAuth                               1.0.2      AksHci
Function        Install-AksHciCsiNfs                               1.0.2      AksHci
Function        Install-AksHciCsiSmb                               1.0.2      AksHci
Function        Install-AksHciGMSAWebhook                          1.0.2      AksHci
Function        Install-AksHciMonitoring                           1.0.2      AksHci
Function        New-AksHciCluster                                  1.0.2      AksHci
Function        New-AksHciClusterNetwork                           1.0.2      AksHci
Function        New-AksHciContainerRegistry                        1.0.2      AksHci
Function        New-AksHciNetworkSetting                           1.0.2      AksHci
Function        New-AksHciProxySetting                             1.0.2      AksHci
Function        New-AksHciStorageContainer                         1.0.2      AksHci
Function        Remove-AksHciCluster                               1.0.2      AksHci
Function        Remove-AksHciClusterNetwork                        1.0.2      AksHci
Function        Remove-AksHciGMSACredentialSpec                    1.0.2      AksHci
Function        Remove-AksHciNode                                  1.0.2      AksHci
Function        Repair-AksHciCerts                                 1.0.2      AksHci
Function        Repair-AksHciClusterCerts                          1.0.2      AksHci
Function        Restart-AksHci                                     1.0.2      AksHci
Function        Set-AksHciCluster                                  1.0.2      AksHci
Function        Set-AksHciConfig                                   1.0.2      AksHci
Function        Set-AksHciRegistration                             1.0.2      AksHci
Function        Sync-AksHciBilling                                 1.0.2      AksHci
Function        Uninstall-AksHci                                   1.0.2      AksHci
Function        Uninstall-AksHciAdAuth                             1.0.2      AksHci
Function        Uninstall-AksHciCsiNfs                             1.0.2      AksHci
Function        Uninstall-AksHciCsiSmb                             1.0.2      AksHci
Function        Uninstall-AksHciGMSAWebhook                        1.0.2      AksHci
Function        Uninstall-AksHciMonitoring                         1.0.2      AksHci
Function        Update-AksHci                                      1.0.2      AksHci
Function        Update-AksHciCluster                               1.0.2      AksHci

[akshcihost001.akshci.local]: PS C:\Users\AzureUser\Documents>
[akshcihost001.akshci.local]: PS C:\Users\AzureUser\Documents>
[akshcihost001.akshci.local]: PS C:\Users\AzureUser\Documents> Get-AksHciCluster
>>

ProvisioningState     : provisioned
KubernetesVersion     : v1.20.5-kvapkg.1
Name                  : my-workload-cluster
ControlPlaneNodeCount : 1
WindowsNodeCount      : 1
LinuxNodeCount        : 1

**Comment by Elektronenvolt** [comment]
This is the correct function: `Set-AksHciCluster –name my-workload-cluster -linuxNodeCount 2 -windowsNodeCount 1`

**Comment by abhilashaagarwala** [comment]
Hey @SurbhiAgarwal12! This seems to be a documentation error and we're working with the right owner. In the meantime, please follow this documentation for scaling your cluster - https://docs.microsoft.com/en-us/azure-stack/aks-hci/set-akshcicluster

**Comment by mattmcspirit** [comment]
This is now fixed - thanks for catching this!

https://github.com/Azure/aks-hci/blob/main/eval/steps/2a_DeployAKSHCI_WAC.md#scale-your-kubernetes-cluster-target-cluster
