### ISSUE TITLE
[BUG] Could not see AKS on WAC

### ISSUE THREAD

**Issue by aszykm** [Azure/aks-hci#112]
**Describe the bug**
I could not see any information about AKS on WAC.
**To Reproduce**
1. Go to Azure Kubernetes Service on HCI Cluster in WAC

**Screenshots**
![image](https://user-images.githubusercontent.com/7985066/127876007-9c03c763-03b7-4eaa-adac-04ea62db347d.png)

**Environment:**
- OS: Windows 10
- Browser Edge
- AKS Extension 1.35.0

**Comment by sushmadharm** [comment]
@aszykm Can you clear your temp folder and try again?

**Comment by aszykm** [comment]
I cleaned up user temp files on Cluster Host and It is working.
%userprofile%\AppData\Local\Temp

Thanks for help.
