### ISSUE TITLE
[BUG] Update from June 1.0.1.10628 to July 1.0.2.10723 failed with kvactl.exe upgrade exit code 1: context deadline exceeded.

### ISSUE THREAD

**Issue by zawachte-msft** [Azure/aks-hci#119]
**Describe the bug**

There is a bug in the June 1.0.1.10628 build of AksHci which causes an excess amount of kubernetes configuration secrets to be created on a cluster.  

We added some code in the upgrade path from June 1.0.1.10628 to July 1.0.2.10723 to clean up these secrets. This added code is sometimes not able to clean up these secrets. Therefore we are failing to upgrade AksHci. 

**To Reproduce**

Install June 1.0.1.10628 build of AksHci. Wait a couple of weeks. Then upgrade to July 1.0.2.10723.

**Expected behavior**

Upgrade to July 1.0.2.10723 succeeds.

**Screenshots**
![b0496291-4bdc-498d-9b32-18871edbe196](https://user-images.githubusercontent.com/45979377/129641286-e714e63b-8ca6-4568-8185-06c020f77e26.png)

**Environment (please complete the following information):**
- OS: N/A
- Browser N/A
- Version N/A
- AKS-HCI Version: June 1.0.1.10628
- Kubernetes Version (i.e. 1.18.8)

**Comment by madhanrm** [comment]
Can you add a workaround?

**Comment by zawachte-msft** [comment]
If you hit this issue please save the following script as `fix_leaked_secrets.ps1`

```ps1
param(
[Parameter(Mandatory=$true)]
[string] $ClusterName,
[Parameter(Mandatory=$true)]
[string] $ManagementKubeConfigPath
)

$ControlPlaneHostName = kubectl get nodes --kubeconfig $ManagementKubeConfigPath -o=jsonpath='{.items[0].metadata.name}'
"Hostname is: $ControlPlaneHostName"

$leakedSecretPath1 = "$ClusterName-template-secret-akshci-cc"
$leakedSecretPath2 = "$ClusterName-moc-kms-plugin"
$leakedSecretPath3 = "$ClusterName-kube-vip"
$leakedSecretPath4 = "$ClusterName-template-secret-akshc"
$leakedSecretPath5 = "$ClusterName-linux-template-secret-akshci-cc"
$leakedSecretPath6 = "$ClusterName-windows-template-secret-akshci-cc"

$leakedSecretNameList = New-Object -TypeName 'System.Collections.ArrayList';
$leakedSecretNameList.Add($leakedSecretPath1) | Out-Null
$leakedSecretNameList.Add($leakedSecretPath2) | Out-Null
$leakedSecretNameList.Add($leakedSecretPath3) | Out-Null
$leakedSecretNameList.Add($leakedSecretPath4) | Out-Null
$leakedSecretNameList.Add($leakedSecretPath5) | Out-Null
$leakedSecretNameList.Add($leakedSecretPath6) | Out-Null

foreach ($leakedSecretName in $leakedSecretNameList)
{
"Deleting secrets with the prefix $leakedSecretName"
$output = kubectl --kubeconfig $ManagementKubeConfigPath exec etcd-$ControlPlaneHostName -n kube-system -- sh -c "ETCDCTL_API=3 etcdctl --cacert /etc/kubernetes/pki/etcd/ca.crt --key /etc/kubernetes/pki/etcd/server.key --cert /etc/kubernetes/pki/etcd/server.crt del /registry/secrets/default/$leakedSecretName --prefix=true"
"Deleted: $output"
}
```

Then, run the following command:

```ps1
.\fix_secret_leak.ps1 -ClusterName (Get-AksHciConfig).Kva.KvaName -ManagementKubeConfigPath (Get-AksHciConfig).Kva.Kubeconfig
```

Then attempt the upgrade again.

```
Update-AksHci
```

**Comment by abhilashaagarwala** [comment]
Assigning this to @EkeleAsonye so we can include this known issue in our troubleshooting guide and direct users here from documentation.

**Comment by v-susbo** [comment]
I've added Ekele's workaround for this known issue to the content: https://docs.microsoft.com/en-us/azure-stack/aks-hci/troubleshoot-known-issues#when-using-powershell-to-upgrade-an-excess-number-of-kubernetes-configuration-secrets-is-created-on-a-cluster

**Comment by abhilashaagarwala** [comment]
Thanks Susan!
