### ISSUE TITLE
[BUG] Add-AksHciNode does not work

### ISSUE THREAD

**Issue by dmc-tech** [Azure/aks-hci#121]
**Describe the bug**
Add-AksHciNode throws an error when trying to add a new host to the cluster. The server is a n existing member of the failover cluster, yet the cmdlet says it is not.

**To Reproduce**
1. Run get-cluster | Get-ClusterNode from one of the cluster nodes to get current list in the failover cluster. confirm name of node to add is there.
2. Run Add-AksHciNode -nodeName <new nodename>
3. See error

**Expected behavior**
I would expect for the Moc and Kva be deployed to the new node in the failover cluster

**Screenshots**
![image](https://user-images.githubusercontent.com/8145761/130115945-e1d4a9ba-49b3-4e50-ae08-fffc14ec0c89.png)

**Environment (please complete the following information):**
- OS: [Azure Stack HCI - preview version ]
- AKS-HCI Version July 2021

**Additional context**
The same behavior is presented when running on the new node, or an existing node. using the latest modules on each

**Collect log files**
- From a PowerShell Admin window run **Get-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by madhanrm** [comment]
Sep release should have this fix. Please feel free to try it out when available and resolve this

**Comment by abhilashaagarwala** [comment]
Closing this bug because a fix was released. Since this is now a year old, please use the latest version and open a fresh bug if it persists.
