### ISSUE TITLE
[BUG] API Server not accessible after 60 days (no update) and cluster is rebooted

### ISSUE THREAD

**Issue by raghavendra-nataraj** [Azure/aks-hci#127]
**Describe the bug**
The Repair-AksHciCerts cmdlet fails if the api server is down. 

**To Reproduce**
1. Install AksHci
2. If AksHci is not upgraded for 60 days and the kms is restarted

**Expected behavior**
1. Kms plugin would not start and this would cause the API server to fail
2. KMS plugin logs would contain the following logs 
`2021/08/02 21:27:53 rpc error: code = Unauthenticated desc = Valid Token Required.
clouduser@moc-la18fmyl0lb [ ~ ]$ sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf logs -n kube-system kms-plugin-moc-la18fmyl0lb -p
2021/08/02 21:27:53 [plugin] start
2021/08/02 21:27:53 starting login to cloud agent
2021/08/02 21:27:53 rpc error: code = Unauthenticated desc = Valid Token Required.`
3. This would required the Repair-AksHciCerts to be run. However this command interact with the API server, which would be down in this case
4. When running the Repair-AksHciCerts you would see the below error

**Screenshots**
![Repair-certs](https://user-images.githubusercontent.com/15914198/133163346-3e348175-a355-4150-9bd5-3621759b568f.png)
**Environment (please complete the following information):**
- AKS-HCI Version (i.e. Public Preview October-2020)
- Kubernetes Version (i.e. 1.18.8)

**Solution**
To fix this issue, we would need to manually fix the token and restart KMS plugin to get the api server back up. The fixing up would require the following steps.

These are the command that are required to manually rotate the token in KMS. Please let me know if any issues or questions

1) Rotate Token
`
$ mocctl.exe security identity rotate --name "KMSPlugin-<cluster-name>-moc-kms-plugin" --encode=false --cloudFqdn (Get-AksHciConfig).Moc.cloudfqdn > cloudlogin.yaml
`

2) Copy token to VM( the ip here refers to the mgmt cluster control plane IP-Address)
`
$ scp -i (Get-AksHciConfig).Moc.sshPrivateKey .\cloudlogin.yaml clouduser@<ip>:~/cloudlogin.yaml
$ ssh -i (Get-AksHciConfig).Moc.sshPrivateKey clouduser@<ip> sudo mv cloudlogin.yaml /opt/wssd/k8s/cloudlogin.yaml
`

3) Restart KMS Plugin/Container
Since it is a static pod we need to start the container
    * Get container ID
`
$ ssh -i (Get-AksHciConfig).Moc.sshPrivateKey clouduser@<ip> "sudo docker container ls | grep 'kms'"
`
The output should have the below fields
`
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
`
The output should look something like this
`
4169c10c9712 f111078dbbe1 "/kms-plugin" 22 minutes ago Up 22 minutes k8s_kms-plugin_kms-plugin-moc-lll6bm1plaa_kube-system_d4544572743e024431874e6ba7a9203b_1
`
    * Restart the contiainer
`
$ ssh -i (Get-AksHciConfig).Moc.sshPrivateKey clouduser@<ip> "sudo docker container kill <Container ID>"
`

**Comment by EkeleAsonye** [comment]
Sent this to Susan to publish in the TSG

**Comment by v-susbo** [comment]
This issue is documented here: https://docs.microsoft.com/en-us/azure-stack/aks-hci/troubleshoot-known-issues#the-api-server-is-not-responsive-after-several-days

**Comment by eponerine** [comment]
@v-susbo - can you please update the docs.microsoft.com article to include the line-break here?

This was updated today:

![image](https://user-images.githubusercontent.com/503974/144535166-2eb189f1-7a64-4933-8f63-c74e5dcada74.png)

This is how it looks on Docs:

![image](https://user-images.githubusercontent.com/503974/144535196-e08fe911-dee2-4196-9127-0f3584138fbc.png)

Depending on the user's environment, if they attempt to copy/paste that, it'll fail.

**Comment by chrisloup** [comment]
This might just be my environment but it stumped us on getting kvactl operational . so just a fyi in case

$ mocctl.exe security identity rotate --name "KMSPlugin-<cluster-name>-moc-kms-plugin" --encode=false --cloudFqdn (Get-AksHciConfig).Moc.cloudfqdn > cloudlogin.yaml


We discovered that the command is wrong, its not <cluster-name> but <aks control plane name>

#kmsplugin name was found in

 mocctl security identity list | find `"kms`"
 name: KMSPlugin-46de3dea-ef08-4cf7-b3af-c67fa42d1e38-moc-kms-plugin
 name: KMSPlugin-akshci1-moc-kms-plugin


mocctl.exe security identity rotate --name "KMSPlugin-46de3dea-ef08-4cf7-b3af-c67fa42d1e38-moc-kms-plugin" --encode=false --cloudFqdn (Get-AksHciConfig).Moc.cloudfqdn > cloudlogin.yaml
