### ISSUE TITLE
[BUG] Sticking with "Waiting for job 'azure-arc-onboarding' to complete" when Install AKS on HCI

### ISSUE THREAD

**Issue by Li-Yanzhi** [Azure/aks-hci#139]
**Describe the bug**
When run "Install-AksHci -Verbose",  after finished some steps and then sticking with "**Waiting for job 'azure-arc-onboarding' to complete**" for long time and then exit with error.

**To Reproduce**
Steps to reproduce the behavior: run following scripts to install AKS on HCI (from MSLab):

```
$ClusterName="AzSHCI-Cluster"
$vSwitchName="vSwitch"
$vNetName="aksvnet"
$VolumeName="AKS"
$Servers=(Get-ClusterNode -Cluster $ClusterName).Name
$VIPPoolStart="10.0.0.100"
$VIPPoolEnd="10.0.0.200"
$resourcegroupname="$ClusterName-rg"

$vnet = New-AksHciNetworkSetting -Name $vNetName -vSwitchName $vSwitchName -vippoolstart $vippoolstart -vippoolend $vippoolend
Set-AksHciConfig -vnet $vnet -imageDir c:\clusterstorage\$VolumeName\Images -workingDir c:\ClusterStorage\$VolumeName\ImageStore -cloudConfigLocation c:\clusterstorage\$VolumeName\Config -ClusterRoleName "$($ClusterName)_AKS" -controlPlaneVmSize 'Standard_D2s_v3'

$subscriptionID="xxxxxxx"
$tenantId = "xxxxxxx"
Set-AksHciRegistration -SubscriptionID $subscriptionID -ResourceGroupName $resourcegroupname -TenantId $tenantId -UseDeviceAuthentication

Install-AksHci -Verbose
```

**Expected behavior**
Script will execute successfully and created a mgmt. cluster.

**Screenshots**
![image](https://user-images.githubusercontent.com/6248137/139869037-d020238f-6417-45c2-8020-ae020b94a24f.png)
![image](https://user-images.githubusercontent.com/6248137/139869367-e76762d3-b4e4-4ca4-b632-23fb5d04d029.png)

**Environment (please complete the following information):**
- OS:  Azure Stack HCI 21H2 Build 20348
- AKS-HCI Version: October 2021 Update , 1.0.5.11028

**Additional context**
Same installation scripts is working on Azure Stack HCI 20H2 & AKS-HCI Version of August 2021 Update

**Comment by zawachte-msft** [comment]
Hey @Li-Yanzhi,

Looks like you are hitting this error because the step of azure-onboarding happened **an hour** after you hit "Install-AksHci". 

We don't ever expect this to be the case. What kind of hardware are you running this on?

**Comment by zawachte-msft** [comment]
Can you do the following.

Clean up.
Run "Install-AksHci"
Wait 20 minutes.

In a new Powershell window run Get-AksHciLogs and upload, please.

**Comment by Elektronenvolt** [comment]
@zawachte-msft regarding the 'hour' - do you talk about the setup step `Enable-AksHciArcConnection -name mycluster` here?

**Comment by Li-Yanzhi** [comment]
> Can you do the following.
> 
> Clean up. Run "Install-AksHci" Wait 20 minutes.
> 
> In a new Powershell window run Get-AksHciLogs and upload, please.

Hi @zawachte-msft attached logs:

[akshcilogs.zip](https://github.com/Azure/aks-hci/files/7465291/akshcilogs.zip)

BTW: I am running the installation script on Azure Nested Virtualization Environment from MSLab (https://github.com/microsoft/MSLab/tree/master/Scenarios/AzSHCI%20and%20Kubernetes) with 2 HCI Nodes, each node has 8 Core & 56GB RAM.

**Comment by zawachte-msft** [comment]
We don't do any validation on nested virtualized setups. I understand that in the past you have been able to deploy with this setup, but as components like Arc add more features, it may put your setup over the edge.

I would suggest just doing a single node deployment on your physical host for a smoother deployment.

As for the logs you sent, I see the deployment progressing **slowly** but not yet at any point of failure. What ended up happening to the deployment?

**Comment by Li-Yanzhi** [comment]
> We don't do any validation on nested virtualized setups. I understand that in the past you have been able to deploy with this setup, but as components like Arc add more features, it may put your setup over the edge.
> 
> I would suggest just doing a single node deployment on your physical host for a smoother deployment.
> 
> As for the logs you sent, I see the deployment progressing **slowly** but not yet at any point of failure. What ended up happening to the deployment?

I re-run the installation process and waited for 3 hours in arc-onboarding step and then exited with error as bellow:

![image](https://user-images.githubusercontent.com/6248137/140347353-d20ab9dc-08e9-4230-97ae-c8c009670488.png)

The detailed AKS HCI logs is here:
[akshcilogs.zip](https://github.com/Azure/aks-hci/files/7475946/akshcilogs.zip)

**Comment by zawachte-msft** [comment]
Also I noticed you are setting the VM Size of the management cluster at Standard_D2s_v3. We don't support going smaller than the default Standard_A4_v2 size.

We will be introducing blocks in future releases.


Also to be clear, we don't support or test nested setups, so even if this works with the default appliance size, there is no guarantee, that future releases will continue to work.

**Comment by Li-Yanzhi** [comment]
> Also I noticed you are setting the VM Size of the management cluster to Standard_D2s_v3. We don't support going smaller than the default Standard_A4_v2 size.
> 
> We will be introducing blocks for this in future releases.
> 
> Also to be clear, we don't support or validate nested setups, so even if this works with the default management cluster size, there is no guarantee that future releases will continue to work.

Thanks @zawachte-msft, after changing parameter **-controlPlaneVmSize** of **Set-AksHciConfig** to default (Standard_A4_V2) or Standard_D4s_v3, the installation succeeded.

The Docs (https://docs.microsoft.com/en-us/azure-stack/aks-hci/reference/ps/set-akshciconfig) for this part is not correct,  in Docs, the default value of **-controlPlaneVmSize** in **Set-AksHciConfig** is **Standard_A2_V2** (2 Core, 4GB RAM) instead of **Standard_A4_V2**, I have submitted a issue for this.

BTW:  It's just for Lab & Learning purposes in this nested virtualization environment.
