### ISSUE TITLE
[BUG] Cannot repair expired certificates when trying to update Management Cluster

### ISSUE THREAD

**Issue by gianniskt** [Azure/aks-hci#145]
The command `Get-AksHciClusterUpdates -name my-cluster` returns the error: 
`C:\Program Files\AksHci\kvactl.exe cluster get-upgrades --clustername my-cluster --kubeconfig "C:\kubeconfig-mgmt" returned a non zero exit code1 [Error: failed to get new provider: failed to create azurestackhci session: Certificate has expired: Expired: Expired]`

I tried then the command: `Repair-AksHciClusterCerts -Name my-cluster -fixCloudCredentials` and it returns: 
`C:\Program Files\AksHci\kvactl.exe cluster repair --clustername my-cluster --kubeconfig "C:\kubeconfig-mgmt" --sshprivatekey "C:\.ssh\akshci_rsa" --tags "Group=clustergroup-my-cluster" --force=False returned a non zero exit code 1 [Error: unknown flag: --tags]`

Also tried the other command: `Repair-AksHciClusterCerts` and it returns the same error.

The cluster has been created 2 months ago, so the certificates on kubeconfig-mgmt have not been expired. The client certificate is validate for 1 year, and the CA Certificate for 10 years.

I tried also to update cluster with the command `Update-AksHci` but the same error with certificate expiration is shown.

**Environment:**
- Windows Server 2019 Datacenter
- AKS-HCI Version: 1.0.3.10901
- Kubernetes Version: v.1.21.2

**Comment by gianniskt** [comment]
Ok, I checked Azure-Arc and saw that the AKS HCI Management Cluster was appearing offline.
I decided to delete the cluster from Azure Arc with command: `az connectedk8s delete -n <name> -g <resource-group>`

Now I am trying to connect the cluster again via: `az connectedk8s connect -n <name> -g <resource-group>`
The specific error is showed up:
`Helm list release failed: Error: list: failed to list: Internal error occurred: unable to transform key "/registry/secrets/azure-arc/azure-arc-connect-privatekey": failed get version from remote KMS provider: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial unix /var/run/kmsPlugin.sock: connect: no such file or directory"`

Have you ever experienced an issue like that?

**Comment by madhanrm** [comment]
https://github.com/Azure/aks-hci/issues/146

**Comment by madhanrm** [comment]
@raghavendra-nataraj ^^

**Comment by gianniskt** [comment]
We decided to uninstall the AKS-HCI, and install it again, so the issue will be closed.
