### ISSUE TITLE
[BUG] "Waiting for pod 'Cloud Operator' to be ready..." at WAC Deployment

### ISSUE THREAD

**Issue by gianniskt** [Azure/aks-hci#153]
Hello,

During Initial Deployment through WAC, it is stuck at "Waiting for pod 'Cloud Operator' to be ready".
I have tried the workaround that is mentioned in this page https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues-installation but it's not working.

I have noticed that at the management control plane cluster, the container `kube-controller-manager` is recreated in a loop.

![image](https://user-images.githubusercontent.com/38279583/142455663-fa961a31-8e42-4631-a9c1-720fd2296bce.png)

I attach the logs of the container.

[logs_kube-controller.txt](https://github.com/Azure/aks-hci/files/7564351/logs_kube-controller.txt)
[kube-controller-kubeletet-logs.txt](https://github.com/Azure/aks-hci/files/7566375/kube-controller-kubeletet-logs.txt)

I noticed an error regarding kms-provider and health checks, but don't know what's the next troubleshooting steps.

Environment:
Windows Server 2019 Datacenter

**Comment by madhanrm** [comment]
From the logs,

"PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"ecpacr.azurecr.io/moc-kms-plugin:v0.1.4\": failed to resolve reference \"ecpacr.azurecr.io/moc-kms-plugin:v0.1.4\": failed to do request: Head \"https://ecpacr.azurecr.io/v2/moc-kms-plugin/manifests/v0.1.4\": dial tcp: lookup ecpacr.azurecr.io on 127.0.0.53:53: server misbehaving" image="ecpacr.azurecr.io/moc-kms-plugin:v0.1.4"

Is there any proxy in the environment? Image Pull seems to be failing

**Comment by gianniskt** [comment]
No, we don't have a proxy in our environment. It's only a firewall and we have allowed Internet Access at the Physical Cluster Servers, and the network that we defined at `Set-AksHciConfig`

**Comment by gianniskt** [comment]
After troubleshooting, the traffic between cluster service & Management VM was not allowed.
Issue was solved by creating the appropriate firewall rule

**Comment by eponerine** [comment]
@gianniskt - what firewall rule did you modify? Can you please provide port/protocol and source/dest?

**Comment by gianniskt** [comment]
@eponerine - I don't remember exactly as it is 5 months ago. However, If I can recall my mind correctly, we had 2 problems:

1) The gateway for the AKS HCI Network (Nodes), had been misconfigured, so the DNS Resolution was not working (e.g. ecpacr.azurecr.io/moc-kms-plugin:v0.1.4). Our network engineers fixed that issue so it was something special to our environment.

2) Traffic between cluster service role (which is located at the Hyper-V Nodes Network) & Management AKS-HCI Virtual Machine was not allowed, so the network engineers created a firewall rule to allow ports between Cluster service role IP & AKS HCI Network

**Comment by eponerine** [comment]
This sounds correct...  there is no documentation stating that if you have multiple VLANs, you need to explicitly have DNS (53) allowed between your "tenant" VLAN and your "management" VLAN and possibly even conditional forwards setup between zones. Crazy stuff for non-flat configurations.

Thanks for the reply!
