### ISSUE TITLE
[BUG] Upgrade fails with Error: failed to patch capi: action failed after 10 attempts: context deadline exceeded

### ISSUE THREAD

**Issue by raghavendra-nataraj** [Azure/aks-hci#154]
**Describe the bug**
When attempting to upgrade cluster an the upgrade fails with the following error even thought the cluster is still up and reachable
`Update Failed [C:\Program Files\AksHci\kvactl.exe upgrade --configfile
"C:\AksHci\1.0.4.10928\yaml\appliance-update.yaml" --kubeconfig
"C:\AksHci\1.0.4.10928\kubeconfig-mgmt" --cloudop "C:\AksHci\1.0.4.10928\cloud-operator.yaml"
--sshprivatekey "C:\AksHci\.ssh\akshci_rsa"  returned a non zero exit code 1 [Error: failed
to patch capi: action failed after 10 attempts: context deadline exceeded]]
`
The kva-webhook enters a deadlock on certificate update

**To Reproduce**
1. Install AksHci and have cluster up running three months
2. Upgrade AksHci

**Expected behavior**
On upgrading AksHci the upgrade would return with the following error
`Update Failed [C:\Program Files\AksHci\kvactl.exe upgrade --configfile
"C:\AksHci\1.0.4.10928\yaml\appliance-update.yaml" --kubeconfig
"C:\AksHci\1.0.4.10928\kubeconfig-mgmt" --cloudop "C:\AksHci\1.0.4.10928\cloud-operator.yaml"
--sshprivatekey "C:\AksHci\.ssh\akshci_rsa"  returned a non zero exit code 1 [Error: failed
to patch capi: action failed after 10 attempts: context deadline exceeded]]
`

**Screenshots**
![image](https://user-images.githubusercontent.com/15914198/142680519-c9e5b106-57d8-4080-b37f-7a7b55194fcb.png)

**Environment (please complete the following information):**
- AKS-HCI Version (Any version)

**Solution**
Restarting the kva-webhook would fix the issue.  Steps are as below

1. Get the kva-webhook pod name
2. Delete the kva-webhook pod 

- [ ] Get the kva-webhook pod name

```
$kubectl.exe get pods --kubeconfig (Get-AksHciConfig).Kva.kubeconfig -A | select-string kva-webhook

This should return the results in the format
NAMESPACE NAME READY STATUS RESTARTS AGE

Example of output
kube-system kva-webhook-******* 1/1 Running 0 5m36s

```

- [ ] Delete the kva-webhook pod
`$kubectl.exe delete pod <kva-webhook-pod-name> --kubeconfig (Get-AksHciConfig).Kva.kubeconfig -n kube-system`

Once this is completed a new kva-webhook pod should be running. We can attempt an upgrade again.

**Comment by madhanrm** [comment]
@mattbriggs

**Comment by mattbriggs** [comment]
@raghavendra-nataraj Thanks!

#in-progress

**Comment by mattbriggs** [comment]
https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues-upgrade#upgrade-fails-with-error-failed-to-patch-capi-action-failed-after-10-attempts-context-deadline-exceeded

**Comment by mattbriggs** [comment]
#please-close

**Comment by abhilashaagarwala** [comment]
Closing because we fixed this.
