### ISSUE TITLE
Eval - "deploy to Azure" button leads to a broken URL

### ISSUE THREAD

**Issue by shayshahak** [Azure/aks-hci#155]
**Describe the bug**
when using the tutorial here:
https://github.com/Azure/aks-hci/blob/main/eval/steps/1_AKSHCI_Azure.md
and clicking on the "Deploy to Azure" button it leads to the following URL which is broken:
https://raw.githubusercontent.com/Azure/aks-hci/october_eval/eval/json/akshcihost.json
instead, it should be directing to this URL:
https://raw.githubusercontent.com/Azure/aks-hci/main/eval/json/akshcihost.json

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- AKS-HCI Version (i.e. Public Preview October-2020)
- Kubernetes Version (i.e. 1.18.8)

**Additional context**

**Collect log files**
- From a PowerShell Admin window run **Get-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by mattmcspirit** [comment]
Thanks for catching this - this should now be fixed, apologies for the inconvenience.
