### ISSUE TITLE
[BUG] Error at Step 7 when deploying AKS on Azure Stack HCI management cluster

### ISSUE THREAD

**Issue by alexsimon1** [Azure/aks-hci#158]
Hello,

i cannot peform Step 7.
I get the following error msg:

PS C:\Users\AzureUser> Set-AksHciRegistration -SubscriptionId $sub -ResourceGroupName $rg
Trace-CmdletError : Exception calling "GetBytes" with "1" argument(s): "Array cannot be null.
Parameter name: chars"
At C:\Program Files\WindowsPowerShell\Modules\AksHci\1.1.19\AksHci.psm1:4595 char:9
+         Trace-CmdletError -ConfigDetails $(Get-TraceConfigDetails) `
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Trace-CmdletError], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException,Trace-CmdletError

Thanks for your help.

**Comment by alexsimon1** [comment]
the ressource group was in the wrong location

**Comment by eponerine** [comment]
Can we bring this back to life? The error message is absolutely worthless in helping users know that the Resource Group location check fails...

... which in all honesty is bogus because who cares where the RG is; the AKS-HCI Resource location matters.
