### ISSUE TITLE
AKS-HCI Deploy Failed(Cloud Agent)

### ISSUE THREAD

**Issue by tunkai** [Azure/aks-hci#162]
Hi Everyone

My deployment information is as follows.......

PS C:\Users\kyle> $vnet = New-AksHciNetworkSetting -name aksnet -vSwitchName "ComputeSwitch" -k8sNodeIpPoolStart "192.168.0.52" -k8sNodeIpPoolEnd "192.168.0.100" -vipPoolStart "192.168.255.0" -vipPoolEnd "192.168.255.254" -ipAddressPrefix "192.168.0.0/16" -gateway "192.168.0.1" -dnsServers "192.168.0.1"
PS C:\Users\kyle> Set-AksHciConfig -imageDir C:\ClusterStorage\aksVolume\Images -workingDir C:\ClusterStorage\aksVolume\ImageStore -cloudConfigLocation C:\ClusterStorage\aksVolume\Config -vnet $vnet -cloudservicecidr "192.168.0.51/16"
PS C:\Users\kyle> Set-AksHciRegistration -subscriptionId "446327c5-b325-4cd8-8eb8-ed66b9558d35" -resourceGroupName "azs-arc-rg"
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code H5AEJVUTB to authenticate.
PS C:\Users\kyle>

PS C:\Users\kyle> Install-akshci -verbose
VERBOSE: [12/22/2021 12:50:21] [AksHci] Initializing environment
VERBOSE: [12/22/2021 12:50:21] [AksHci] Importing Configuration
VERBOSE: [12/22/2021 12:50:21] [AksHci] Importing Configuration Completed
VERBOSE: [12/22/2021 12:50:23] [AksHci] Saving Configuration for Module AksHci to configuration file

WARNING: Start-FailoverClusterResource failed
Exception [Failed to start cluster resource [MOC Cloud Agent Service]. ExtendedStatus: CurrentState: Offline, LastOperationStatusCode: 0, StatusInformation:  0.. Exception caught is: 'An error occurred while
attempting to bring the resource 'MOC Cloud Agent Service' online.']
Stacktrace [at Start-FailoverClusterResource, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Common.psm1: line 2810                                                                                         at Add-FailoverClusterGenericRole, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Common.psm1: line 2981                                                                                                    at Install-CloudAgent, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1310                                                                                                                   at Install-MocAgents, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1229
at Initialize-Cloud, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1135
at Install-MocInternal, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1078
at Install-Moc, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 207
at Install-AksHciInternal, C:\Program Files\WindowsPowerShell\Modules\AksHci\1.1.20\AksHci.psm1: line 3811
at Install-AksHci, C:\Program Files\WindowsPowerShell\Modules\AksHci\1.1.20\AksHci.psm1: line 747
at <ScriptBlock>, <No file>: line 1]
WARNING: Install-Moc failed.
Exception [This typically indicates an issue happened while registering the resource name as a computer object with the domain controller and/or the DNS server. Please check the domain controller and DNS logs
for related error messages. Error: [Start-FailoverClusterResource failed
Exception [Failed to start cluster resource [MOC Cloud Agent Service]. ExtendedStatus: CurrentState: Offline, LastOperationStatusCode: 0, StatusInformation:  0.. Exception caught is: 'An error occurred while
attempting to bring the resource 'MOC Cloud Agent Service' online.']
Stacktrace [at Start-FailoverClusterResource, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Common.psm1: line 2810
at Add-FailoverClusterGenericRole, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Common.psm1: line 2981
at Install-CloudAgent, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1310
at Install-MocAgents, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1229
at Initialize-Cloud, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1135
at Install-MocInternal, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1078
at Install-Moc, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 207
at Install-AksHciInternal, C:\Program Files\WindowsPowerShell\Modules\AksHci\1.1.20\AksHci.psm1: line 3811
at Install-AksHci, C:\Program Files\WindowsPowerShell\Modules\AksHci\1.1.20\AksHci.psm1: line 747
at <ScriptBlock>, <No file>: line 1]]]
Stacktrace [at Add-FailoverClusterGenericRole, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Common.psm1: line 2987
at Install-CloudAgent, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1310
at Install-MocAgents, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1229
at Initialize-Cloud, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1135
at Install-MocInternal, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 1078
at Install-Moc, C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.16\Moc.psm1: line 207
at Install-AksHciInternal, C:\Program Files\WindowsPowerShell\Modules\AksHci\1.1.20\AksHci.psm1: line 3811
at Install-AksHci, C:\Program Files\WindowsPowerShell\Modules\AksHci\1.1.20\AksHci.psm1: line 747
at <ScriptBlock>, <No file>: line 1]
InnerException[Failed to start cluster resource [MOC Cloud Agent Service]. ExtendedStatus: CurrentState: Offline, LastOperationStatusCode: 0, StatusInformation:  0.. Exception caught is: 'An error occurred
while attempting to bring the resource 'MOC Cloud Agent Service' online.']
VERBOSE: [12/22/2021 12:51:44] [AksHci] Initializing environment
VERBOSE: [12/22/2021 12:51:44] [AksHci] Importing Configuration
VERBOSE: [12/22/2021 12:51:44] [AksHci] Importing Configuration Completed
WARNING: Name resolution of ca-ab926f4a-d032-452e-9227-a646b2f025e3.azshci.local failed
VERBOSE: [12/22/2021 12:52:50] [AksHci] Warning: Billing records collection failed
VERBOSE: [12/22/2021 12:52:50] [AksHci]   Unable to find command C:\Program Files\AksHci\mocctl.exe
VERBOSE: [12/22/2021 12:52:51] [AksHci] Collecting AksHci information...
VERBOSE: Found matching provider: AKSHCI
VERBOSE: The AKSHCI provider writes events to the AKSHCI log.
VERBOSE: Log akshci will be queried
VERBOSE: [12/22/2021 12:52:53] [AksHci] Compressing Logs...
VERBOSE: [12/22/2021 12:52:56] [AksHci] Zip File is located at ""C:\ClusterStorage\aksVolume\ImageStore\1.0.6.11122\akshcilogsnjecw5zd.5zt.zip""
VERBOSE: [12/22/2021 12:52:56] [AksHci] Done
VERBOSE: [12/22/2021 12:52:56] [AksHci] Saving Configuration for Module AksHci to configuration file

I don’t know where there is a configuration error , Maybe someone can help me ........ Thank you so much

**Comment by Twistednumbers** [comment]
WEould like to know how you got this Moc issue resolved? Was it the OU ?
