### ISSUE TITLE
[BUG] Install-AksHci hangs in the "Waiting for azure-arc-onboarding to complete" stage before timing out

### ISSUE THREAD

**Issue by raghavendra-nataraj** [Azure/aks-hci#164]
**Describe the bug**
AksHci installation hangs in the "Waiting for azure-arc-onboarding to complete" before timing out when
1. If service principal is used in AksHci Registration (Set-AksHciRegistration)
2. Az.Accounts powershell modules version(2.7.x) installed

The [Az.Accounts 2.7.x](https://www.powershellgallery.com/packages/Az.Accounts/2.7.0) versions removes the 'ServicePrincipalSecret' and 'CertificatePassword' in 'PSAzureRmAccount' which is used by AksHci for acr-onboarding. 

**To Reproduce**
1. Install Az.Accounts powershell modules version(>= 2.7.0)
2. Set-AksHciRegistration using service principal
3. Install-AksHci

**Expected behavior**
1. AksHci installation hangs in the "Waiting for azure-arc-onboarding to complete"
2. Azure-arc-onboarding pods goes into crash loop
![MicrosoftTeams-image](https://user-images.githubusercontent.com/15914198/150441302-a46d397d-0554-4b68-bf16-4b592a27636f.png)
3. The Azure-arc-onboarding pods error with the following error
`Starting onboarding process
ERROR: variable CLIENT_SECRET is required`

**Environment (please complete the following information):**
- AKS-HCI Version - Any
- Az.Accounts Version (>= 2.7.0)

**Solution:**
Uninstall Az.Accounts modules with versions 2.7.x
`Uninstall-Module -Name  Az.Accounts -RequiredVersion 2.7.0 -Force `

**Comment by mattbriggs** [comment]
@raghavendra-nataraj  Thanks!

#in-process

**Comment by madhanrm** [comment]
@mattbriggs  - can you provide the TSG link

**Comment by mattbriggs** [comment]
https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues-installation?#install-akshci-hangs-in-the-waiting-for-azure-arc-onboarding-to-complete-stage-before-timing-out
