### ISSUE TITLE
[BUG] Mocctl certificate expired if not used for more than 60days

### ISSUE THREAD

**Issue by raghavendra-nataraj** [Azure/aks-hci#168]
**Describe the bug**
AksHci  uses the mocctl command line tool to communicate with MocStack for performing Moc related operations. The certificate used by mocclt command to communicate with cloudagent has an expiry is 60 days. The mocctl command would renew the certificate automatically when is used closed to its expiry (after ~42 days). If the command is not used frequently, the certificate expires. 

**To Reproduce**
1. Install AksHci and if no operation involving the mocctl is performed for 60 days. 

**Expected behavior**
`System.Collections.Hashtable.generic_non_zero 1 [Error: Certificate has expired: Expired]`

**Screenshots**
<img width="902" alt="moccertificate" src="https://user-images.githubusercontent.com/15914198/151596868-6c6f5679-1a0c-4223-950c-695a2d27288e.png">

**Solution**
The user is expected to re-login once the certificate expires. Execute the following command in Powershell to re-login. 
`Repair-MocLogin`

**Comment by sethmanheim** [comment]
Added to AKS-HCI TSGs.
