### ISSUE TITLE
[BUG] Moc agent log rotation is failing

### ISSUE THREAD

**Issue by in3xes** [Azure/aks-hci#170]
**Describe the bug**
Moc agents are expected to keep only the last 100 agent logs. They are supposed to delete the older logs. However, the log rotation is not happening and logs keep getting accumulated consuming disk space. 

**To Reproduce**
Install AksHci and have a cluster up and running till the number of agent logs exceeds 100.

**Expected behavior**
At the time of the nth log creation, the agents are expected to delete the n-100th log if they exist. 

**Solution**
1. Modify the cloud agent and node agents' logconf files.
    Cloud agent logconfig is located at $(Get-MocConfig)['cloudConfigLocation']\log\logconf
    Node agent logconfig is located at $(Get-MocConfig)['cloudConfigLocation']\log\logconf

2. Change the value of Limit to 100 and Slots to 100 and save the config files.

3. Restart the cloud agent and node agents to pick up these changes.

This mitigation starts the log rotation only after 100 new logs are generated from the agent restart. If there are already n agent logs at the time of restart, log rotation will start only after n+100 logs are generated.

**Comment by madhanrm** [comment]
@mattbriggs

**Comment by mattbriggs** [comment]
https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues-installation?#moc-agent-log-rotation-is-failing
