### ISSUE TITLE
[BUG] Update of host OS (HCI -> HCIv2) breaks AKS-HCI installation with: OutOfCapacity

### ISSUE THREAD

**Issue by apluchik** [Azure/aks-hci#171]
**Describe the bug**
Running an OS update on a host with an AKS HCI deployment can cause the deployment to enter a bad state and fail day 2 operations.  The MOC NodeAgent Services may fail to start up on the hosts that underwent update, and all MOC calls to the nodes will fail.

**To Reproduce**
Update a cluster with an existing AKS HCI deployment from HCI to HCIv2.
_This issue only happens occasionally_

**Expected behavior**
After OS update day 2 AKS HCI operations, such as New-AksHciCluster will fail, stating that the MOC nodes are **OutOfCapacity**. eg error:

``` System.Collections.Hashtable.generic_non_zero1 [Error: failed to create nic test-load-balancer-whceb-nic for machinetest-load-balancer-whceb: unable to create VM network interface: failed to create network interface test-load-balancer-whceb-nic in resource group clustergroup-test: rpc error: code = Unknown desc = Location 'MocLocation' doesn't expose any nodes to create VNIC 'test-load-balancer-whceb-nic' on: OutOfCapacity] ```

**Solution**
Starting the `wssdagent` Moc NodeAgent Service on all affected nodes will solve this issue, and bring the deployment back to a good state. Running the following command can accomplish this:

``` Get-ClusterNode -ErrorAction Stop | ForEach-Object { Invoke-Command -ComputerName $_ -ScriptBlock { Start-Service wssdagent -WarningAction:SilentlyContinue } } ```

**Comment by madhanrm** [comment]
@mattbriggs

**Comment by mattbriggs** [comment]
https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues-upgrade#update-of-host-os-hci-to-hciv2-breaks-aks-hci-installation

**Comment by madhanrm** [comment]
This should be fixed
