### ISSUE TITLE
[BUG] AKS cluster backup with velero fails with the below error

### ISSUE THREAD

**Issue by amkarmak** [Azure/aks-hci#172]
**Describe the bug**
AKS cluster backup with velero fails with the below error. Url https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks

I have reported this to the url https://github.com/MicrosoftDocs/azure-stack-docs/issues/1844. Got the suggestion to post the issue here as well.

url:- https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks

I have configured the backup. But it fails with below messages.. Any suggestion will be a great help.

time="2022-02-01T07:42:10Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = unable to get all required config values: the following keys do not have values: resourceGroup" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:197" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:175"

**To Reproduce**
follow the backup mentioned on the url https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks

**Expected behavior**

**Screenshots**
I have configured the backup. But it fails with below messages.. Any suggestion will be a great help.

time="2022-02-01T07:42:10Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = unable to get all required config values: the following keys do not have values: resourceGroup" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:197" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:175"

**Environment (please complete the following information):**
- AKS-HCI Version (i.e. Public Preview October-2020)
- Kubernetes Version (i.e. 1.18.8)

**Additional context**

**Collect log files**
- From a PowerShell Admin window run **Get-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by mkostersitz** [comment]
Hello @amkarmak,
It looks like you followed the documentation for AKS to enable Velero on AKS-HCI and not documented way for AKS-HCI which is here [https://docs.microsoft.com/en-us/azure-stack/aks-hci/backup-workload-cluster](https://docs.microsoft.com/en-us/azure-stack/aks-hci/backup-workload-cluster). If you undo your steps, and re-deploy with the above documentation and see an error please open a new issue and attach logs from Get-AksHciLogs.
