### ISSUE TITLE
[BUG] Update of host OS (HCI -> HCIv2) breaks AKS-HCI installation: Cannot reach management cluster

### ISSUE THREAD

**Issue by apluchik** [Azure/aks-hci#174]
**Describe the bug**
Running an OS update on a host with an AKS HCI deployment can cause the deployment to enter a bad state, rendering the management cluster's api server unreachable and fail day 2 operations. The kube-vip pod will not be able to apply VIP configuration to the interface, and as a result the VIP will be unreachable.

**To Reproduce** 
Update a cluster with an existing AKS HCI deployment from HCI to HCIv2 then try running commands that attempt to reach the management cluster such as `Get-AksHciCluster`.

**Expected behavior**
Any operations that attempt to reach the management cluster will fail with errors such as:

``` 
PS C:\Users\wolfpack> Get-AksHciCluster                                                                                 
C:\Program Files\AksHci\kvactl.exe cluster list --kubeconfig="C:\ClusterStorage\Volume1\Msk8s\WorkingDir\1.0.8.10223\kubeconfig-mgmt" System.Collections.Hashtable.generic_non_zero 1 [Error: failed to connect to the cluster: action failed after 9
attempts: Get "https://10.193.237.5:6443/api?timeout=10s": net/http: request canceled while waiting for connection
(Client.Timeout exceeded while awaiting headers)]
At C:\Program Files\WindowsPowerShell\Modules\Kva\1.0.22\Common.psm1:2164 char:9
+         throw $errMessage
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (C:\Program File...iting headers)]:String) [], RuntimeException
    + FullyQualifiedErrorId : C:\Program Files\AksHci\kvactl.exe cluster list --kubeconfig="C:\ClusterStorage\Volume1\Msk8s\WorkingDir\1.0.8.10223\kubeconfig-mgmt" System.Collections.Hashtable.generic_non_zero 1 [Error: failed to connect to the cluster: action failed after 9 attempts: Get "https://10.193.237.5:6443/api?timeout=10s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)]
```

**Solution**
Restarting the kube-vip container will bring the deployment back to a good state:

1. Get container ID:
` $ ssh -i (Get-AksHciConfig).Moc.sshPrivateKey clouduser@<ip> "sudo crictl ls | grep 'kube-vip'" `
The output should look something like this; with the container ID being the first value ` 4a49a5158a5f8 `
```
4a49a5158a5f8       7751a28bb5ce1       28 minutes ago      Running             kube-vip                         1                   cf9681f921a55
```

2. Restart the contiainer
`$ ssh -i (Get-AksHciConfig).Moc.sshPrivateKey clouduser@<ip> "sudo crictl stop <Container ID>"`

**Comment by madhanrm** [comment]
@mattbriggs

**Comment by mattbriggs** [comment]
https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues-upgrade?#update-of-host-os-hci-to-hciv2-breaks-aks-on-azure-stack-hci-installation-cannot-reach-management-cluster

**Comment by abhilashaagarwala** [comment]
Closing this since this has been fixed. We'll open it again if we see this being an issue again.
