### ISSUE TITLE
[BUG] vNIC goes missing after a machine reboot.

### ISSUE THREAD

**Issue by in3xes** [Azure/aks-hci#184]
**Describe the bug**
If AksHcinodes are rebooted one after the other, some of the virtual machines lose the vNICs attached to them. This causes the VMs to lose network connectivity and the cluster goes into a bad state.

**To Reproduce**
1. Reboot one AksHci Node
2. Wait for the node to complete the reboot. The node needs to be marked "Up" in the failover cluster
3. Reboot the other nodes
4. Repeat

**Expected behavior**
The cluster state should be healthy. All the VMs should have NICs attached to them.

**Environment (please complete the following information):**
- AKS-HCI Version - 1.0.8.10223 or older

**Solution**
Use the MOC commands to add the vNIC to the VM using the following steps:

1. Get vNIC name for the VM
`(Get-MocVirtualMachine -group <group> -name <vmname>).virtualmachineproperties.networkprofile.networkinterfaces`
or 
`mocctl.exe compute vm get --name <vmname> --group <group>`

2. Connect the vNIC to the VM
`Connect-MocNetworkInterface -name <vnicname> -group <group> -virtualMachineName <vmname>`
or
` mocctl.exe compute vm nic add --name <vnicname> --vm-name <vmname> --group <group>`

3. If the vNIC connect command fails, try disconnect and connect again. Following is the command for vNIC disconnect.
`Disconnect-MocNetworkInterface -name <vnicname> -group <group> -virtualMachineName <vmname>`
or 
` mocctl.exe compute vm nic remove --name <vnicname> --vm-name <vmname> --group <group>`

**Comment by madhanrm** [comment]
@in3xes , which release has this fix it is Feb or Apr?

**Comment by in3xes** [comment]
@madhanrm I think it went into April. Definitely not February.
