### ISSUE TITLE
Error: Waiting for pod Cloud Operator failed: Back-off pulling image "ecpacr.azurecr.io/cloud-operator:v1.0.13": FailFastPodCondition

### ISSUE THREAD

**Issue by SantosVictorero** [Azure/aks-hci#188]
I am installing AksHci version 1.0.10.10513 

Issues #99 and  #153 say that this bug has been corrected but I am still getting the error:

I have set all the firewall policies in my VLANs, everything else is working until this error:

RecordId             : 11680
ProviderName         : AksHci
ProviderId           : 
LogName              : AKSHCI
ProcessId            : 
ThreadId             : 
MachineName          : CBSI-AKS...
UserId               : 
TimeCreated          : 6/23/2022 12:30:43 PM
ActivityId           : 
RelatedActivityId    : 
ContainerLog         : AKSHCI
MatchedQueryIds      : {}
Bookmark             : System.Diagnostics.Eventing.Reader.EventBookmark
LevelDisplayName     : Information
OpcodeDisplayName    : Info
TaskDisplayName      : 
KeywordsDisplayNames : {Classic}
Properties           : {System.Diagnostics.Eventing.Reader.EventProperty}

Message              : Install-AksHci -  create --configfile 
                       "e:\ClusterStorage\Volume1\ImageStore\1.0.10.10513\yaml\appliance.yaml" --outfile 
                       "e:\ClusterStorage\Volume1\ImageStore\1.0.10.10513\kubeconfig-mgmt"  --azure-creds-stdin 
                       returned a non zero exit code 1 [Error: Waiting for pod Cloud Operator failed: Back-off pulling 
                       image "ecpacr.azurecr.io/cloud-operator:v1.0.13": FailFastPodCondition
                       ].

Any documentation about the settings for this cases (multiple VLANs)?

**Comment by SantosVictorero** [comment]
BTW,

Just in case someone else runs into the same issue, I solved this error by adding a DNS service on the VLAN interface of the FortiGate: 

![image](https://user-images.githubusercontent.com/1824105/175430175-903ab115-2beb-44bd-ae61-5c6ad09115a9.png)

**Comment by azpoul** [comment]
@SantosVictorero - where did you add this DNS Service? We also have a FortiGate 600E setup with our HCI cluster, and are seeing the exact same issue with the 'Cloud Operator'. When I click on 'DNS', the menu looks quite different to yours.
![Skærmbillede 2022-07-04 162414](https://user-images.githubusercontent.com/76207445/177174154-76ec70ce-e4e8-4344-b5e8-b73f249e8b19.png)

**Comment by azpoul** [comment]
Nevermind - the feature "DNS Server" was hidden.
