### ISSUE TITLE
Error while updating AksHci

### ISSUE THREAD

**Issue by SantosVictorero** [Azure/aks-hci#196]
I got this error while updating AksHci:

![image](https://user-images.githubusercontent.com/1824105/179416824-4df64aa2-63c6-42a6-95cd-21ef6fcef272.png)

I looks like the update completed successfully.

**Comment by Elektronenvolt** [comment]
Hi Santos
Looks like you had the 1.22.6 Kubernetes images already in the image store from a previous update.

The error message: I recently learned that all PS windows needs to be closed after `Update-Module -Name AksHci...` and before `Update-AksHci` to load the latest modules. The docs can be misunderstood right now about this. I've seen the same error message during an update of one of my clusters in the past.
By doing an ` Import-Module -Name AksHci -Force`  after Update-Module, or by re-opening the PS window after Update-Module this should not show up again.

**Comment by SantosVictorero** [comment]
Hi Georg,

Thanks for your reply and update.

Yes, I think that I forgot to close the PS window before Update-AksHci.
