### ISSUE TITLE
[BUG] https://aka.ms/akshciteams - This form doesn't exist

### ISSUE THREAD

**Issue by OEI-Cgray** [Azure/aks-hci#201]
**Describe the bug**
There is a broken link on this page, https://github.com/Azure/aks-hci, within:
Meet the product team in Microsoft Teams (click the link to join): https://aka.ms/akshciteams fill in the form and we will add you to the channel ASAP.

**To Reproduce**
1. Go to https://aka.ms/akshciteams
2. See error

**Expected behavior**
A form to fill out.

**Comment by mkostersitz** [comment]
Looks like the form was accidentally deleted a month or so ago. I am working to get it back online.

**Comment by mkostersitz** [comment]
This has been fixed
