### ISSUE TITLE
[BUG] MOC agents don't start after an upgrade failure to June

### ISSUE THREAD

**Issue by in3xes** [Azure/aks-hci#204]
**Describe the bug**
When AksHci fails to upgrade from May to June, the expectation is that AksHci reverts to May and continues to function. But it leaves MOC agents in a stopped state. Manual attempts to start the agent don't bring them up.

**To Reproduce**

1. Install AksHci PowerShell module version 1.1.36
2. Upgrade AksHci. If the upgrade fails, AksHci falls back to May release, but MOC agents don't come up.

**Expected behavior**
If the AksHci upgrade fails, the expectation is that AksHci reverts to the previous release and continues to function without any issues

**Symptoms**

-> _Mismatch between AksHci version and MOC versions_
`Get-AksHciVersion`
1.0.10.10513
`Get-MocVersion`
1.0.11.10707

-> _Mismatch between `Get-MocVersion` and `wssdcloudagent.exe version`_
`Get-MocVersion` indicates that the June build is installed while ``wssdcloudagent.exe version` indicates that the May build is installed.

-> _MOC agent services' image path has deployment id parameter_
Use the following command to print the image path for the cloud agent:
`reg query "HKLM\System\CurrentControlSet\Services\wssdcloudagent"`

Example output:
"C:\Program Files\AksHci\wssdcloudagent.exe" --service --basedir "base dir" --cloudagentfqdn "cloudagent fqdn" --dotfolderpath "dot folder path" --objectdatastore "data store" --clusterresourcename "cluster name" --certificatevalidityfactor 1 **--deploymentid "deployment id"**

Use the following command to print the image path for the node agent:
`reg query "HKLM\System\CurrentControlSet\Services\wssdagent"`

Example output:
"C:\Program Files\AksHci\wssdagent.exe" --service --basedir "base dir" --cloudloginfile "cloud login file path" --dotfolderpath "dotfolder path" --nodeagentfqdn "node fqdn" --objectdatastore "object data store" --wssdproviderspec "provider spec" **--deploymentid "deployment id"**

**Mitigation**
Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Services\wssdcloudagent" -Name ImagePath -Value 'above cloud agent image path without the deployment id'

Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Services\wssdagent" -Name ImagePath -Value 'above node agent image path without the deployment id'

**Comment by leslielin-5** [comment]
TSG published https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues-upgrade#moc-agents-don-t-start-after-an-upgrade-failure
