### ISSUE TITLE
[BUG] WAC Extension import error

### ISSUE THREAD

**Issue by jaromirk** [Azure/aks-hci#21]
**Describe the bug**
Unable to import extension to WAC in GW Mode. 

```
Invoke-WebRequest : {"error":{"code":"PathTooLongException","message":"The specified path, file name, or both are too
long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248
characters."}}
At C:\Program Files\windows admin center\PowerShell\Modules\ExtensionTools\ExtensionTools.psm1:236 char:17
+     $response = Invoke-WebRequest @params
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Failed to get the extensions
At C:\Program Files\windows admin center\PowerShell\Modules\ExtensionTools\ExtensionTools.psm1:238 char:9
+         throw "Failed to get the extensions"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to get the extensions:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to get the extensions
```
**To Reproduce**

Adding aka.ms/WSLab scenario

**Expected behavior**
Importing extension should work.

**Environment (please complete the following information):**

see wslab scenario
[LabConfig.ps1.txt](https://github.com/Azure/aks-hci/files/5268369/LabConfig.ps1.txt)
[Scenario.ps1.txt](https://github.com/Azure/aks-hci/files/5268370/Scenario.ps1.txt)

**Comment by mattatmsft** [comment]
Hi Joramir - 

Right now AKS HCI deployment requires the WAC gateway to be Windows 10.  We will have an update soon to provide support for service mode / WAC installation on Server products, and this is one of the issues that will be covered by that update.

In addition, it's important to make sure that the WAC gateway machine is not part of the physical cluster that you're deploying AKS HCI on.

**Comment by dineshgovindasamy** [comment]
Hi Joramir,

PowerShell modules today doesn't work remotely. you have to use them from being inside the HCI cluster. we will add remote installation functionality in our future release. we will capture this in our roadmap.

**Comment by jaromirk** [comment]
Hi all! Thank you! Is there any workaround how to invoke Initialize-AksHCINode? Like using CredSSP, scheduled job as system... I can script all. The idea is to prepare WSLab scenario that would be easy (just pasting script to management machine). THX!

**Comment by BenjaminArmstrong** [comment]
@jaromirk - There are two issues being discussed here.  Can I ask you to open a seperate issue - so we can have one tracking the WAC issue and one tracking the PowerShell issue?

**Comment by jaromirk** [comment]
OK! Will do.

**Comment by mattatmsft** [comment]
I have confirmed, this fix is in the October release (PP2).
