### ISSUE TITLE
[BUG] Install-AksHCI checks for space on c: + typo

### ISSUE THREAD

**Issue by jaromirk** [Azure/aks-hci#23]
**Describe the bug**
Install-AkSHCI is checking space on c: and you have typos there ("minumum" - should be "minimum")

```
[09/24/2020 01:19:42] Verifying host limits on AzSHCI2

Drive 'C:' has 51 GB free
A minumum of 40 GB disk space is required on drive 'C:'
Host has 13 GB free memory
A minumum of 10 GB memory is required
```

**To Reproduce**

Just run Install-AksHCI

**Expected behavior**

Should check space of volume that is configured for aks (c:\clusterstorage\something)

**Comment by dineshgovindasamy** [comment]
@nwoodmsft  : Add checks to check ClusterStorage if multinode and CSV is passed as image dir.

**Comment by nwoodmsft** [comment]
This is fixed in the forthcoming November release.

**Comment by abhilashaagarwala** [comment]
Closing bug as this has been fixed.
