### ISSUE TITLE
[BUG] Cluster controlplane - certificate expired - Unable to connect to the server: x509:

### ISSUE THREAD

**Issue by raghavendra-nataraj** [Azure/aks-hci#233]
**Describe the bug**
Target cluster not accessible when control plane certificates fail to renew. When trying to reach out the cluster, the kubectl command errors with the following error 
```
certificate expired - Unable to connect to the server: x509: certificate has expired or is not yet valid: current time 2022-07-26T12:24:15-04:00 is after 2022-07-15T15:01:07Z
```

**To Reproduce**
1. Install AksHci
2. Install target cluster
3. Turn off cluster(vms) for more than 4 days. 
4. Turn the cluster on again

**Expected behavior**
The target cluster should be unreachable. Any kubectl command run against target cluster should return with an error message similar to this 
```
certificate expired - Unable to connect to the server: x509: certificate has expired or is not yet valid: current time 2022-07-26T12:24:15-04:00 is after 2022-07-15T15:01:07Z
```

**Solution** 
1. Run the following command to renew the generate certificate manually
```
Update-AksHciClusterCertificates  -Name my-workload-cluster -fixKubeletCredentials
```
2. Generate new credentials
```
Get-AksHciCredential -name <clustername>
```
Give it a few minutes and try the kubectl command again for the cluster to be available again. 

**Note**
There is a known bug in before AksHci version 1.0.14.x. 
If the control plane vm has the name pattern other than ***-control-plane-***, the **Update-AksHciClusterCertificates** command may not work. We would need to update the certificate by logging into the control plane VM.

1. Find the ip address of the target cluster control plane VM.
2. ssh into the vm using
```
ssh -i (get-mocconfig).sshPrivateKey clouduser@<ip>
```
3. List the cert tatoo files
```
sudo ls /etc/kubernetes/pki/cert-tattoo-*
```
4. Generate certificates using each file listed in the above command
```
sudo /usr/bin/cert-tattoo-provision CreateCertsWithAltNames <absolute-path-of-cert-tattoo-file>
```

**Comment by sethmanheim** [comment]
Added to AKS-HCI known issues.
