### ISSUE TITLE
[BUG] Install-AksHci or Initialize-AksHciNode should check/install RSAT-Clustering-PowerShell

### ISSUE THREAD

**Issue by jaromirk** [Azure/aks-hci#24]
**Describe the bug**
If you run Install-AksHCI, you it will fail because it tries to use Clustering posh. There is no check nor code, that would install rsat.

**To Reproduce**

Skip installing RSAT-Clustering-PowerShell and run install aks-hci

**Expected behavior**
There should be check in initialize-akshcinode, that validates readiness of hci nodes (such as RSAT-Clustering-PowerShell). 

**Screenshots**
sorry, I already cleaned the lab. But if you want repro, just skip this step in wslab scenario 
https://github.com/microsoft/WSLab/blob/462137922e0974b2c8d99ed9e4034b3362c674b8/Scenarios/AzSHCI%20and%20Kubernetes/Scenario.ps1#L96

**Comment by dineshgovindasamy** [comment]
will be fixed as part of October Release
