### ISSUE TITLE
[BUG] Uninstall-AksHCI is not cleaning cluster resources (ownergroup ca-154f2102-734b-4631-be78-0d802ce9cf71)

### ISSUE THREAD

**Issue by jaromirk** [Azure/aks-hci#25]
**Describe the bug**
Uninstall-AksHCI is not cleaning cluster objects (I think it might be under certain conditions, triage needed I guess)

**To Reproduce**
I think this was caused when I did not install failover clustering rsat and installed akshci (install-akshci). The script failed, and I had to cancel. Cluster resources were created, and even if I ran Uninstall-akshci, resources were still there, so Install-akshci was failing.

I had to manually clean all resources in clustergroup ca-154f2102-734b-4631-be78-0d802ce9cf71 + AD object.

**Expected behavior**
Uninstall-akshci should clean all - object from ad, and cluster resources

**Comment by jaromirk** [comment]
hmm.. maybe I changed config before uninstall... therefore if that GUID in name is generated during set-akshciconfig, uninstall was not aware of resources. Why not using deterministic OwnerGroup name that would always identify Kubernetes resources?

**Comment by jaromirk** [comment]
![image](https://user-images.githubusercontent.com/9829838/94128307-4799e080-fe5a-11ea-824c-95e190a077c1.png)

In my case I named resource AzSHCI-Cluster_AKS... but it can be anything as I would then identify right group (in case you would generate name and in case more resource group would exist) by resource Network Name

**Comment by zawachte-msft** [comment]
Hey jaromirk,

So we do clean up cluster resources but we are aware of an issue that is the following...

1. Run Install-AksHci with an account that doesn't have the proper AD role or Failover Clustering setup on the host.
2. Fail on Install-AksHci.
3. Run Uninstall-AksHci and have that fail to clean up AD objects.

Does this sound like it is what happened to you?

**Comment by jaromirk** [comment]
yup.

**Comment by mkostersitz** [comment]
Thanks for reporting this issue. It is a known issue as @zawachte-msft pointed out. We are working on improving the behavior.

**Comment by BenjaminArmstrong** [comment]
@mkostersitz - please add to known issues

**Comment by mkostersitz** [comment]
This has been added to the known issues list
