### ISSUE TITLE
[BUG] LinuxNodeVMSize is ignored in New-AksHciCluster

### ISSUE THREAD

**Issue by jaromirk** [Azure/aks-hci#32]
**Describe the bug**
When running New-AksHciCluster -clusterName demo -linuxNodeCount 1 -linuxNodeVmSize Standard_A2_v2, the VM that is created has 8GB RAM.

According this table it should have just 4.

```PowerShell
$global:vmSizeDefinitions =
@(
    # Name, CPU, MemoryGB
    ([VmSize]::Default, "4", "4"),
    ([VmSize]::Standard_A2_v2, "2", "4"),
    ([VmSize]::Standard_A4_v2, "4", "8"),
    ([VmSize]::Standard_D2s_v3, "2", "8"),
    ([VmSize]::Standard_D4s_v3, "4", "16"),
    ([VmSize]::Standard_D8s_v3, "8", "32"),
    ([VmSize]::Standard_D16s_v3, "16", "64"),
    ([VmSize]::Standard_D32s_v3, "32", "128"),
    ([VmSize]::Standard_DS2_v2, "2", "7"),
    ([VmSize]::Standard_DS3_v2, "2", "14"),
    ([VmSize]::Standard_DS4_v2, "8", "28"),
    ([VmSize]::Standard_DS5_v2, "16", "56"),
    ([VmSize]::Standard_DS13_v2, "8", "56"),
    ([VmSize]::Standard_K8S_v1, "4", "2"),
    ([VmSize]::Standard_K8S2_v1, "2", "2"),
    ([VmSize]::Standard_K8S3_v1, "4", "6"),
    ([VmSize]::Standard_NK6, "6", "12"),
    ([VmSize]::Standard_NV6, "6", "64"),
    ([VmSize]::Standard_NV12, "12", "128")

)
```
**To Reproduce**
follow WSLab scenario 
https://github.com/microsoft/WSLab/tree/dev/Scenarios/AzSHCI%20and%20Kubernetes

**Screenshots**

![image](https://user-images.githubusercontent.com/9829838/94206237-4225b000-fec5-11ea-9f27-94377c7d7401.png)

**Comment by dineshgovindasamy** [comment]
@jaromirk  you are looking at the Load Balancer size. 

NAME
    New-AksHciCluster

SYNOPSIS


SYNTAX
    New-AksHciCluster [-clusterName] <String> [[-kubernetesVersion] <String>] [[-controlPlaneNodeCount] <Int32>] [[-linuxNodeCount] <Int32>] [[-windowsNodeCount] <Int32>] [[-controlplaneVmSize] <String>]
    [[-loadBalancerVmSize] <String>] [[-linuxNodeVmSize] <String>] [[-windowsNodeVmSize] <String>] [<CommonParameters>]


DESCRIPTION
    Adds a worker cluster to the deployment.

Linux Node VM Size points to Linux Worker node
loadBalancerVmSize - LB VM size
windowsNodeVmSize - Windwos VM Size
