### ISSUE TITLE
[BUG] Creating cluster will get stuck on waiting for Kubernetes API

### ISSUE THREAD

**Issue by jaromirk** [Azure/aks-hci#33]
**Describe the bug**
Creating cluster will get stuck on waiting for Kubernetes API

**To Reproduce**
Follow WSLab scenario 
https://github.com/microsoft/WSLab/tree/dev/Scenarios/AzSHCI%20and%20Kubernetes

**Screenshots**
![image](https://user-images.githubusercontent.com/9829838/94206360-8c0e9600-fec5-11ea-931b-57d8483d910d.png)

**Comment by dineshgovindasamy** [comment]
@jaromirk : please get us logs.
Most likely we are failing to create VMs. look at  Hyper-V Event Viewer logs for any errors in creating the VM.

**Comment by jaromirk** [comment]
Does this help? 

```
Failed to open attachment 'C:\CLUSTERSTORAGE\AKS\IMAGES\B35F3109C7C4D71\CLUSTERGROUP-MANAGEMENT-LOAD-BALANCER-D20FA3B0\DATA\SEED.ISO'. Error: 'One or more arguments are invalid'.
```

**Comment by jaromirk** [comment]
[Uploading akshcilogs.zip…]()

**Comment by jaromirk** [comment]
[akshcilogs.zip](https://github.com/Azure/aks-hci/files/5281261/akshcilogs.zip)

**Comment by zawachte-msft** [comment]
@jaromirk and I were chatting.

Bringing the conversation here. The logs show that the infrahosts were low on memory.
```
failed to create or get machine: cannot create vm: rpc error: code = Unknown desc = Unable to find a Node that satisfies the input requirement. Total Nodes [2]: OutOfCapacity
```
@jaromirk is going to try again with more RAM.

**Comment by jaromirk** [comment]
Increased amount of memory and all is OK.

I'll modify wslab scenario to create smallest VMs possible

```PowerShell
$ClusterName="AzSHCI-Cluster"
Invoke-Command -ComputerName $ClusterName -ScriptBlock {
    New-AksHciCluster -clusterName demo -linuxNodeCount 1 -linuxNodeVmSize Standard_A2_v2 -controlplaneVmSize Standard_A2_v2 -loadBalancerVmSize Standard_A2_v2 #smallest possible VMs
}
```

![image](https://user-images.githubusercontent.com/9829838/94740838-8c9aa700-0373-11eb-975d-168df31c0844.png)

**Comment by zawachte-msft** [comment]
🎉🎉🎉

**Comment by jaromirk** [comment]
I updated wslab scenario, so it now also works on 16GB RAM Azshci VMs.

**Comment by dineshgovindasamy** [comment]
@nwoodmsft :  Improve diagnostics to VM Start failures rather than waiting for 2hours to deploy mgmt cluster.

**Comment by abhilashaagarwala** [comment]
@nwoodmsft Can you update if this bug has been resolved in the latest release?

**Comment by SouthPawCode** [comment]
I'm encountering this issue in both a deployment done with MSLab or if I walk through it manually, using WAC or PS using the latest March release. Has this been reported by anyone else? I've found no viable workaround to get past it. The Cluster-management host is running and resources are fine. each host has 128GB.

**Comment by abhilashaagarwala** [comment]
Hey @SouthPawCode - Can you please create another bug and attach logs for your error? There are multiple reasons why you might be getting the "waiting for API server" error and it's extremely tough for us to help you without logs. You can gather logs using the "Get-AksHciLogs" command.

**Comment by abhilashaagarwala** [comment]
Closing this bug due to inactivity. Please reopen a new one if you face the issue again. Make sure you install AKS-HCI's GA release - https://github.com/Azure/aks-hci/releases/tag/AKS-HCI-2105
