### ISSUE TITLE
[BUG] RemoteException: The underlying connection was closed: error received on step 5- Review + Create

### ISSUE THREAD

**Issue by dmc-tech** [Azure/aks-hci#37]
**Describe the bug**
On the final step of setting up AKS via the extension from within the HCI Cluster in WAC, I receive the following error:

Failed with errors
Duration: 0 minutes 7 seconds
localhost: (1) RemoteException: The underlying connection was closed: An unexpected error occurred on a send. (2) RemoteException: The property 'StatusCode' cannot be found on this object. Verify that the property exists. (3) RemoteException: The property 'content' cannot be found on this object. Verify that the property exists. (4) RemoteException: The property 'contentid' cannot be found on this object. Verify that the property exists. (5) RemoteException: The property 'contentid' cannot be found on this object. Verify that the property exists. (6) RemoteException: The property 'contentid' cannot be found on this object. Verify that the property exists. (7) RemoteException: Index was outside the bounds of the array. (8) RemoteException: Index was outside the bounds of the array. (9) RemoteException: Index was outside the bounds of the array. (10) RemoteException: Index was outside the bounds of the array. (11) RemoteException: The property 'name' cannot be found on this object. Verify that the property exists. (12) RemoteException: Cannot index into a null array. (13) RemoteException: Cannot index into a null array. (14) RemoteException: Exception calling "IndexOf" with "2" argument(s): "Value cannot be null. Parameter name: array"

**To Reproduce**
1. Follow the Set Up Azure Kubernetes Service wizard from within the AKS Extension.
2. After the step 'Host Configuration and package install, the error appears.

**Expected behavior**
The AKS cluster is deployed successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/8145761/94657404-515b9200-02f9-11eb-8fe2-16c29f6570de.png)

**Environment (please complete the following information):**
- OS: Windows 10 Enterprise 
- Browser Chrome
- Version : AKS xtension: 0.314.0
[aggregated-gateway-logs.zip](https://github.com/Azure/aks-hci/files/5303919/aggregated-gateway-logs.zip)

- AKS-HCI Version : Public Preview 1
- Kubernetes Version (i.e. 1.18.6)

**Additional context**

**Collect log files**
- From a PowerShell Admin window run **Collect-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by dineshgovindasamy** [comment]
@mattatmsft

**Comment by abhilashaagarwala** [comment]
@dmc-tech can I close this bug if it is not repro-ing with the latest release (Feb update)?

**Comment by abhilashaagarwala** [comment]
Closing this bug for now after talking to @dmc-tech. Can reopen if needed.
