### ISSUE TITLE
[BUG] Get-SMEUILogs throws error when wac directory does not exist

### ISSUE THREAD

**Issue by dmc-tech** [Azure/aks-hci#38]
**Describe the bug**
Get-SMEUILogs.ps1 throws an error when run on a system where the %USERPROFILE%/wac directory does not exist

**To Reproduce**
1. Run get-SMEUILogs.ps1 from an elevated session
2. Enter params (running on local WAC system, tried with and without -NoCredentialPrompt)
3. See error C:\nupkg\Get-SMEUILogs.ps1 : Something went wrong while writing out logs to destination(win10wac): Could not find a part of the path 
'C:\Users\*user*\wac\aggregated-gateway-logs.json'.

**Expected behavior**
The command completes successfully and the logs are generated

**Screenshots**

![image](https://user-images.githubusercontent.com/8145761/94660296-66d2bb00-02fd-11eb-9479-1ca5ad352228.png)

**Environment (please complete the following information):**
- OS: Windows 10 Enterprise
- Browser N/A
- Version 
- AKS-HCI Version Public Preview 1
- Kubernetes Version N/A

**Additional context**

The issue is resolved by manually creating %userprofile%\wac directory

**Comment by dineshgovindasamy** [comment]
@mattatmsft

**Comment by abhilashaagarwala** [comment]
@dmc-tech can I close this bug if it is not repro-ing with the latest release (Feb update)?

**Comment by dmc-tech** [comment]
This issue still exists in the Feb release

**Comment by abhilashaagarwala** [comment]
Can you try this on the AKS-HCI GA release and let us know if it persists? https://github.com/Azure/aks-hci/releases/tag/AKS-HCI-2105

**Comment by mkostersitz** [comment]
This should be fixed in GA. We are not able to reproduct this issue anymore
