### ISSUE TITLE
[BUG] When using the PowerShell module to deploy the AKS cluster, an error is generated when adding the wssdcloudagent generic role

### ISSUE THREAD

**Issue by dmc-tech** [Azure/aks-hci#40]
**Describe the bug**
When using the PowerShell module to deploy the AKS cluster, an error is generated when adding the wssdcloudagent generic role.  The following output is received when running the install-akshci cmdlet:

 - Adding wssdcloudagent cluster generic service role (hci-aks-test1)
Add-ClusterGenericServiceRole : Static network 10.18.73.0/25 was not configured. Please use -StaticAddress to use this network or use -IgnoreNetwork to ignore it.
At C:\Program Files\WindowsPowerShell\Modules\akshci\0.2.5\AksHci.psm1:445 char:9
+         Add-ClusterGenericServiceRole -Name $global:config["clusterRo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Add-ClusterGenericServiceRole], ClusterCmdletException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.FailoverClusters.PowerShell.AddClusterGenericServiceRoleCommand
 - Waiting for cloudagent API endpoint to be accessible...
 - Warning: this depends on DNS propogation and can take between and 10-30 minutes in some environments...

The environment uses DHCP.

This can be resolved by running on another HCI node: 
Add-ClusterGenericServiceRole -Name hci-aks-test1 -ServiceName wssdcloudagent -StaticAddress <ip-address/mask> | Out-Null

Once it has run, the rest of the install-akshci script completes successfully.

**To Reproduce**
1. From a HCI Node, set the AKS config
Set-AksHciConfig -deploymentType MultiNode -wssdImageDir c:\ClusterStorage\Volume01\hci-aks-test1 -cloudConfigLocation c:\ClusterStorage\Volume01\hci-aks-test1  -vnetname ComputeSwitch -clusterRoleName hci-aks-test1
2. run Install-akshci
3. wait until the error appears
4. To fix, from another HCI node, run
Add-ClusterGenericServiceRole -Name hci-aks-test1 -ServiceName wssdcloudagent -StaticAddress <ip-address/mask> | Out-Null
5. Once the role has installed, the cript continues.

**Expected behavior**
The cluster role is created without manual intervention, *or* a parameter is exposed which allows to specify the Static IP Address

**Screenshots**
![image](https://user-images.githubusercontent.com/8145761/94683797-03f21b80-031f-11eb-8a85-f35273d0f7de.png)

![image](https://user-images.githubusercontent.com/8145761/94684768-6c8dc800-0320-11eb-941e-9e8957de5db9.png)

**Environment (please complete the following information):**

- AKS-HCI Version (i.e. Public Preview 1)
- Kubernetes Version (i.e. 1.18.6)

**Comment by dineshgovindasamy** [comment]
@dmc-tech : This usually means Failover Clustering is not able to detect a DHCP network in your HCI Cluster. Today AKSHCI works only with DHCP networks. we are adding support for static networks in the next release which will be out in November. For now is it possible to configure a DHCP network in your HCI cluster?

**Comment by dmc-tech** [comment]
DHCP is available in the environment.  All the Management and worker nodes use DHCP and are on the same network as the cluster

**Comment by dineshgovindasamy** [comment]
@JocelynBerrendonner ^^^

**Comment by JocelynBerrendonner** [comment]
@dmc-tech : Could you open an elevated powershell command and run "Test-Cluster". The command will produce an HTML validation report. In report, please check all the interfaces attached to all the "Cluster and Client" networks have DHCP enabled.

**Comment by dineshgovindasamy** [comment]
Targeted for October Release
