### ISSUE TITLE
[BUG] Adding a AKS cluster deployed via PowerShell to WAC, error 'The cluster is unreachable'.

### ISSUE THREAD

**Issue by dmc-tech** [Azure/aks-hci#42]
**Describe the bug**
When Adding a AKS cluster deployed via PowerShell to WAC, error 'The cluster is unreachable'. from the same system that WAC is running on, using kubectl and the same kubeconfig file, I can connect successfully

**To Reproduce**
1. Go to Add on the WAC main screen
2. Click on 'Kubernetes clusters (preview) - Add''
3. Select a Kubeconfig file for the AKS cluster 
4. Select the Cluster and User from the drop downs
5. Click on Submit
6. See error ' The cluster is unreachable.'

**Expected behavior**
I would expect the AKS cluster to be added to WAC.

**Screenshots**
WAC error:
![image](https://user-images.githubusercontent.com/8145761/94695609-07d96a00-032e-11eb-8edf-0773e9e4a1ae.png)

kubectl success:
![image](https://user-images.githubusercontent.com/8145761/94695773-3e16e980-032e-11eb-874d-59e174b0c18a.png)

**Environment (please complete the following information):**
- OS: WIndows 10
- Browser: Edge Chromium
- AKS-HCI Version: Public Preview 1
- Kubernetes Version: 1.18.6

**Additional context**

**Collect log files**
- From a PowerShell Admin window run **Collect-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”
[aggregated-gateway-logs (2).zip](https://github.com/Azure/aks-hci/files/5306111/aggregated-gateway-logs.2.zip)

**Comment by comnam90** [comment]
Hitting the same issue

**Comment by eszych** [comment]
Same issue here...

**Comment by abhilashaagarwala** [comment]
@dmc-tech, @eszych, @comnam90 Can we close this bug if its not repro-ing in the latest release (ie Feb update)?

**Comment by abhilashaagarwala** [comment]
Closing this bug due to inactivity. Please reopen if this persists in AKS-HCI GA build - https://github.com/Azure/aks-hci/releases/tag/AKS-HCI-2105
