### ISSUE TITLE
[BUG] Onboarding check (job/azure-arc-onboarding) error

### ISSUE THREAD

**Issue by jaromirk** [Azure/aks-hci#48]
**Describe the bug**

Checking onboarding does not work as per error below

![image](https://user-images.githubusercontent.com/9829838/96888832-52aa5580-1486-11eb-8c82-689ef0ccf3cf.png)

**To Reproduce**

https://github.com/microsoft/WSLab/tree/master/Scenarios/AzSHCI%20and%20Kubernetes

https://github.com/microsoft/WSLab/blob/master/Scenarios/AzSHCI%20and%20Kubernetes/Scenario.ps1#L287-L290

**Comment by jaromirk** [comment]
Looks like it has problem to onboard cluster. It does not appear in Azure 
![image](https://user-images.githubusercontent.com/9829838/97003341-957a3500-153b-11eb-935b-be0d640059fb.png)

**Comment by zawachte-msft** [comment]
Hey @jaromirk. So I think we need to fix the script output, but you need to switch to using the target cluster kubeconfig to watch the arc onboarding progress.

```ps
Get-AksHciCredential -clusterName demo
```

This will put the kubeconfig in your userprofile so you can run ...

```ps
kubectl logs job/azure-arc-onboarding -n azure-arc-onboarding --follow
```

**Comment by jaromirk** [comment]
Great! I modified code and all looks good now!

```Powershell
#onboard cluster
Invoke-Command -ComputerName $ClusterName -ScriptBlock {
    #generage kubeconfig first
    Get-AksHciCredential -clusterName demo
    #onboard
    Install-AksHciArcOnboarding -clusterName $using:AKSClusterName -tenantId $using:tenantID -subscriptionId $using:subscriptionID -resourcegroup $using:resourcegroup -Location $using:location -clientId $using:ClientID -clientSecret $using:UnsecureSecret
}
```

```PowerShell
#check onboarding
#generate kubeconfig (this step was already done)
<#
Invoke-Command -ComputerName $ClusterName -ScriptBlock {
    Get-AksHciCredential -clusterName demo
}
#>
#copy kubeconfig
$session=New-PSSession -ComputerName $ClusterName
Copy-Item -Path "$env:userprofile\.kube" -Destination $env:userprofile -FromSession $session -Recurse
#copy kubectl
Copy-Item -Path $env:ProgramFiles\AksHCI\ -Destination $env:ProgramFiles -FromSession $session -Recurse
#validate onboarding
& "c:\Program Files\AksHci\kubectl.exe" logs job/azure-arc-onboarding -n azure-arc-onboarding --follow
```

I'll push changes to scenario. THX!

**Comment by jaromirk** [comment]
![image](https://user-images.githubusercontent.com/9829838/97029169-58bf3580-155d-11eb-94ba-8b618e3b61a1.png)

**Comment by jaromirk** [comment]
![image](https://user-images.githubusercontent.com/9829838/97029329-92903c00-155d-11eb-89ca-98f7db080077.png)

**Comment by zawachte-msft** [comment]
Awesome! Looking good! Arc is so cool!

**Comment by zawachte-msft** [comment]
btw if you want to download the kubeconfig to a specific location you can run

```ps
Get-AksHciCredential -clusterName demo -outputLocation C:\path\to\whereever
```

**Comment by jaromirk** [comment]
cool! BTW do you have some example on how to deploy app to cluster using arc? or some demo on how to utilize arc with Kubernetes cluster... I would add it to scenario. I'm also thinking to create separate subnet/vlan for Kubernetes cluster (I can create multiple subnets in wslab).

**Comment by zawachte-msft** [comment]
@abhilashaagarwala can help you with the first request.

As for the second ... today we only support a single vlan for the whole deployment. Multiple subnets/vlans is coming soon!

**Comment by abhilashaagarwala** [comment]
Hello! I can absolutely help you! Please follow these links to deploy applications to Azure Arc, and using Azure services like Monitor and Policy on top:
1. [Deploy an application using Gitops](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/use-gitops-connected-cluster)
2. [Deploy an application using Helm charts](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/use-gitops-with-helm)
3. [Use Azure Policy to govern cluster configuration](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/use-azure-policy)
4. [Set up Azure Monitor for Containers with Arc](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-enable-arc-enabled-clusters)
5. [Admission control policies using Azure Policy](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/policy-for-kubernetes)

**Comment by jaromirk** [comment]
cool! thank you!
