### ISSUE TITLE
[BUG] AksHci day0 install with PwSh stuck at testing cloud agent endpoint

### ISSUE THREAD

**Issue by erjosito** [Azure/aks-hci#49]
**Describe the bug**
Installing AksHci via `Install-AksHci` on a 2-node HCI cluster deployed on Azure VMs. The installer runs more or less OK, meaning that there are some errors. First, at the very beginning it fails to delete the cloudagent directory both in the node where the `Install-AksHci` is running and in the neighbor node:

```
[10/23/2020 04:24:36] Cleaning up files on WIN-MUCC37Q1OIO
 - Removing yaml on WIN-MUCC37Q1OIO...
 - Removing cloudagent directory on WIN-MUCC37Q1OIO...
Access is denied
    + CategoryInfo          : NotSpecified: (:) [Remove-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand
    + PSComputerName        : WIN-MUCC37Q1OIO
 - Removing nodeagent directory on WIN-MUCC37Q1OIO...
 - Removing cloudagent registry on WIN-MUCC37Q1OIO...
 - Removing nodeagent registry on WIN-MUCC37Q1OIO...
 - Removing image directory on WIN-MUCC37Q1OIO...
 - Downloaded images will be preserved
 - Removing all of the installation directory contents on WIN-MUCC37Q1OIO...

[10/23/2020 04:24:37] Cleaning up files on WIN-PSIERIALC37
 - Removing yaml on WIN-PSIERIALC37...
 - Removing cloudagent directory on WIN-PSIERIALC37...
Access is denied
    + CategoryInfo          : NotSpecified: (:) [Remove-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand
    + PSComputerName        : WIN-PSIERIALC37
 - Removing nodeagent directory on WIN-PSIERIALC37...
 - Removing cloudagent registry on WIN-PSIERIALC37...
 - Removing nodeagent registry on WIN-PSIERIALC37...
 - Removing image directory on WIN-PSIERIALC37...
 - Downloaded images will be preserved
 - Removing all of the installation directory contents on WIN-PSIERIALC37...
```

Secondly, and probably more relevant, it fails at enabling DNS locally:

```
- Adding wssdcloudagent cluster generic service role (ca-7b01383a-150c-490b-af5d-141572ce4d9a)

 -  - Installing missing feature 'DNS-Server-Tools' ...
Name                                    OwnerNode       State
----                                    ---------       -----
ca-7b01383a-150c-490b-af5d-141572ce4d9a WIN-PSIERIALC37 Failed
Path   :
Online : True

 - Waiting for cloudagent API endpoint to be accessible...
 - Warning: this depends on DNS propogation and can take between and 10-30 minutes in some environments...
 - [10/23/2020 04:31:08] Testing cloudagent endpoint: ca-7b01383a-150c-490b-af5d-141572ce4d9a.azshci.local
 - [10/23/2020 04:31:29] Testing cloudagent endpoint: ca-7b01383a-150c-490b-af5d-141572ce4d9a.azshci.local
 - [10/23/2020 04:31:49] Testing cloudagent endpoint: ca-7b01383a-150c-490b-af5d-141572ce4d9a.azshci.local
 - [10/23/2020 04:32:09] Testing cloudagent endpoint: ca-7b01383a-150c-490b-af5d-141572ce4d9a.azshci.local
 - [10/23/2020 04:32:29] Testing cloudagent endpoint: ca-7b01383a-150c-490b-af5d-141572ce4d9a.azshci.local
 - [10/23/2020 04:32:50] Testing cloudagent endpoint: ca-7b01383a-150c-490b-af5d-141572ce4d9a.azshci.local
[goes on for 40min and counting]
```

**To Reproduce**
Following the instructions to deploy HCI on Azure, and to deploy AKS on HCI

**Expected behavior**
`Install-AksHci` to work without errors

**Screenshots**
See logs above

**Environment (please complete the following information):**
- AKS-HCI Version (i.e. Public Preview 1)
```
PS C:\users\labadmin\Windows Admin Center> get-module -name akshci
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.2.8      AksHci                              {Get-AksHciCluster, Get-AksHciCredential, Get-AksHciKubernetesVersion, Get-AksHciLogs...}
```
- Kubernetes Version (i.e. 1.18.6)

**Additional context**

**Collect log files**
- From a PowerShell Admin window run **Collect-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by dineshgovindasamy** [comment]
@BenjaminArmstrong : Can you please share the installation steps in Azure?

**Comment by Mohkam** [comment]
is there any workaround for this issue ?

**Comment by zawachte-msft** [comment]
Did you try without this flag?
```
-forceDnsReplication true 
```

**Comment by Mohkam** [comment]
Yes, I was able get pass this error by providing service cidr.
Now I am on a different error that we are already on thread with Pieter from dell. On my official email address.
Lets continue over there.

Kind Regards,
Mohkam Uddin
+92-323-3339733
MIT, MCSA, MCP, MCTS, JNCIS
linkedin.com/in/mohkamdin<https://linkedin.com/in/mohkamdin>

**Comment by BenjaminArmstrong** [comment]
Providing update for this thread - today we do not support evaluating AKS-HCI in Azure VMs.  And there are numerous known issues with this.  We are working on it.

**Comment by Mohkam** [comment]
for those who are still facing this - setting cloudServiceCIDR and clusterRoleName before installation helped me passed through this error. 
`Set-AksHciConfig -deploymentType MultiNode -wssdImageDir "C:\ClusterStorage\HCICSV1\" -cloudConfigLocation "C:\ClusterStorage\HCICSV1\" -vnetName ConvergedSwitch -clusterRoleName hciaks  -cloudServiceCidr 10.10.120.11/24 
`
@BenjaminArmstrong My environment is also virtualized but on HyperV and not in Azure. Please confirm if that is supported.

**Comment by BenjaminArmstrong** [comment]
Closing this issue - as we now support evaluation in an Azure VM and have an evaluation guide available here: https://github.com/Azure/aks-hci/blob/main/eval/readme.md
