### ISSUE TITLE
[BUG] Creating Kubernetes Cluster fails in WAC

### ISSUE THREAD

**Issue by dmc-tech** [Azure/aks-hci#51]
**Describe the bug**
When creating a Kubernetes workload cluster via WAC, I received the following error:

Failed with errors
Error: failed to get new provider: failed to create azurestackhci session: error: could not read cloudconfig file: open cloudconfig: The system cannot find the file specified.

msazure.visualstudio.com/msazure/msk8s/mgmtappl.git/sdk/pkg/appliance/provider.newProvider /home/nick/goroot/src/dev.azure.com/msazure/msk8s/mgmtappl/sdk/pkg/appliance/provider/provider.go:55 msazure.visualstudio.com/msazure/msk8s/mgmtappl.git/sdk/pkg/appliance/provider.New /home/nick/goroot/src/dev.azure.com/msazure/msk8s/mgmtappl/sdk/pkg/appliance/provider/provider.go:49 msazure.visualstudio.com/msazure/msk8s/mgmtappl.git/sdk/pkg/appliance.newApplianceClient /home/nick/goroot/src/dev.azure.com/msazure/msk8s/mgmtappl/sdk/pkg/appliance/client.go:86 msazure.visualstudio.com/msazure/msk8s/mgmtappl.git/sdk/pkg/appliance.New /home/nick/goroot/src/dev.azure.com/msazure/msk8s/mgmtappl/sdk/pkg/appliance/client.go:73 msazure.visualstudio.com/msazure/msk8s/mgmtappl.git/cmd/appliance/cmd.runClusterCreate /home/nick/goroot/src/dev.azure.com/msazure/msk8s/mgmtappl/cmd/appliance/cmd/cluster_create.go:50 msazure.visualstudio.com/msazure/msk8s/mgmtappl.git/cmd/appliance/cmd.glob..func2 /home/nick/goroot/src/dev.azure.com/msazure/msk8s/mgmtappl/cmd/appliance/cmd/cluster_create.go:38 github.com/spf13/cobra.(*Command).execute /home/nick/goroot/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 github.com/spf13/cobra.(*Command).ExecuteC /home/nick/goroot/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 github.com/spf13/cobra.(*Command).Execute /home/nick/goroot/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887

msazure.visualstudio.com/msazure/msk8s/mgmtappl.git/cmd/appliance/cmd.Execute /home/nick/goroot/src/dev.azure.com/msazure/msk8s/mgmtappl/cmd/appliance/cmd/root.go:46 main.main /home/nick/goroot/src/dev.azure.com/msazure/msk8s/mgmtappl/cmd/appliance/main.go:22 runtime.main /home/nick/go/src/runtime/proc.go:203 runtime.goexit /home/nick/go/src/runtime/asm_amd64.s:1357

**To Reproduce**
1. Add - Kubernetes Cluster in WAC
2. Click through / enter config for prereqs/Basics/Node Pools/Networing/Integration.
3. Click on Create under Review + Create

**Expected behavior**
The application cluster is created.

**Screenshots**
![2020-10-27 09_38_37-Window](https://user-images.githubusercontent.com/8145761/97286170-1470b580-183b-11eb-8168-a9a3c399bc71.png)

**Environment (please complete the following information):**
- OS: Windows 10
- Browser: Edge Chrome
- Version 86.0.622.51
- AKS-HCI Version (i.e. Public Preview October)
- Kubernetes Version: 
[aggregated-gateway-logs.zip](https://github.com/Azure/aks-hci/files/5445024/aggregated-gateway-logs.zip)

1.18.8

**Additional context**

**Collect log files**
- From a PowerShell Admin window run **Collect-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by mattatmsft** [comment]
@dmc-tech - were you able to run: Collect-AksHciLogs on the cluster?

**Comment by dmc-tech** [comment]
@mattatmsft Sorry, I didn't get to do that.  I've since redeployed the management and a workload cluster using PowerShell (successfully).  I'll uninstall that and try again

**Comment by dmc-tech** [comment]
@mattatmsft  I have collected the HCI logs from the HCI cluster in question - they are 57MB in size so cannot upload here

**Comment by dmc-tech** [comment]
I've emailed you the link

**Comment by abhilashaagarwala** [comment]
@dmc-tech can I close this bug if it is not repro-ing with the latest release (Feb update)?

**Comment by abhilashaagarwala** [comment]
Closing this bug for now after talking to @dmc-tech. Can reopen if needed.
