### ISSUE TITLE
[BUG] Deploying an AKS cluster via Install-AksHci PowerShell Cmdlet throws an error

### ISSUE THREAD

**Issue by dmc-tech** [Azure/aks-hci#52]
**Describe the bug**
Deploying an AKS cluster via Install-AksHci PowerShell Cmdlet throws an error:

Error: open C:\ClusterStorage\Volume01\wssd\kubeconfig-mgmt: The system cannot find the path specified.
C:\Program Files\AksHci\kvactl.exe create --configfile C:\wssd\yaml\appliance.yaml --outfile C:\ClusterStorage\Volume01\wssd\kubeconfig-mgmt failed to execute []
At C:\Program Files\WindowsPowerShell\Modules\akshci\0.2.8\Common.psm1:1248 char:9
+         throw "$command $arguments failed to execute [$err]"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (C:\Program File...d to execute []:String) [], RuntimeException
    + FullyQualifiedErrorId : C:\Program Files\AksHci\kvactl.exe create --configfile C:\wssd\yaml\appliance.yaml --outfile C:\ClusterStorage\Volume01\wssd\kubeconfig-mgmt failed to execute []

**To Reproduce**
1. Import AKsHCI Module from Oct 2020 release on one of the HCI Nodes
2. Run Initialize-AksHciNode
3. Set-AksHciConfig -deploymentType MultiNode -wssdImageDir 'C:\ClusterStorage\Volume01\wssdImages' -cloudConfigLocation C:\ClusterStorage\Volume01\aks-clus01-config -vnetName Computeswitch
4. Install-AksHCI
5. Error is thrown
6. Run & 'C:\Program Files\AksHci\kvactl.exe' create --configfile C:\wssd\yaml\appliance.yaml --outfile C:\ClusterStorage\Volume01\wssd\kubeconfig-mgmt

10-27-2020 06:18:35 [Status] azurestackhciProvider: RetrieveKubeconfig
10-27-2020 06:18:35 [Status] The appliance kubeconfig is already present. Resuming an existing deployment...
Error: open C:\ClusterStorage\Volume01\wssd\kubeconfig-mgmt: The system cannot find the path specified.

7. create the WSSD directory and run the command in step 6 again.  
10-27-2020 06:19:25 [Status] azurestackhciProvider: RetrieveKubeconfig
10-27-2020 06:19:25 [Status] The appliance kubeconfig is already present. Resuming an existing deployment...
10-27-2020 06:19:25 [Status] Waiting for API server...
10-27-2020 06:19:25 [Status] Waiting for pod 'Cloud Operator' to be ready...
10-27-2020 06:19:25 [Status] Waiting for pod 'Cluster API core' to be ready...
10-27-2020 06:19:25 [Status] Waiting for pod 'Bootstrap kubeadm' to be ready...
10-27-2020 06:19:25 [Status] Waiting for pod 'Control Plane kubeadm' to be ready...
10-27-2020 06:19:25 [Status] Waiting for pod 'Cluster API core Webhook' to be ready...
10-27-2020 06:19:25 [Status] Waiting for pod 'Bootstrap kubeadm Webhook' to be ready...
10-27-2020 06:19:25 [Status] Waiting for pod 'Control Plane kubeadm Webhook' to be ready...
10-27-2020 06:19:25 [Status] azurestackhciProvider: PerformPostOperations
10-27-2020 06:19:25 [Status] azurestackhciProvider: Waiting for pod 'AzureStackHCI Provider' to be ready...
10-27-2020 06:19:25 [Status] azurestackhciProvider: Waiting for pod 'AzureStackHCI Provider Webhook' to be ready...

**Expected behavior**
I would expect that if the WSSD dir is required on the CSV, then it is created, or the config is placed into the cloudconfiglocation directory specified

**Screenshots**
![image](https://user-images.githubusercontent.com/8145761/97308420-c1a5f680-1858-11eb-9df1-acaa9680ce6d.png)

![image](https://user-images.githubusercontent.com/8145761/97308504-d6828a00-1858-11eb-8b13-1aa672b43c4e.png)

![image](https://user-images.githubusercontent.com/8145761/97308577-ed28e100-1858-11eb-9240-c58fa23fde9d.png)

**Environment (please complete the following information):**
- OS: HCI OS

- AKS-HCI Version Oct 2020
- Kubernetes Version 1.18.8

**Additional context**
to fix this, I uninstalled-aksHCI, set the config , created the WSSD directory on the CSV and ran the install again

**Collect log files**
- From a PowerShell Admin window run **Collect-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by madhanrm** [comment]
Can you please try this using the December release bits following the documentation.

**Comment by abhilashaagarwala** [comment]
@dmc-tech Can you close this bug if its not repro-ing in the latest release (ie Feb update)?

**Comment by abhilashaagarwala** [comment]
Closing this bug for now after talking to @dmc-tech. Can reopen if needed.
