### ISSUE TITLE
[BUG] Unable to add a Kubernetes cluster via WAC due to Persistent Storage location option not being available

### ISSUE THREAD

**Issue by dmc-tech** [Azure/aks-hci#54]
**Describe the bug**
Unable to deploy a K8s cluster via WAC as the persistent storage location option not being available in the Integration step.  The 'Next: Review + Create' button is blank.

**To Reproduce**

![image](https://user-images.githubusercontent.com/8145761/97415860-9f19e900-18fd-11eb-82aa-763faa64ff93.png)

**Expected behavior**
To be able to proceed to the 'Review + Create' option

**Environment (please complete the following information):**
- OS: Windows 10
- Browser Edge Chromium
- Version 86.0.622.51
- AKS-HCI Version Oct-2020
- Kubernetes Version 1.18.8

**Additional context**
On the same HCI cluster, I had previously deployed an AKS HCI app cluster using the PowerShell module successfully.  This was uninstalled to test another bug I had logged for WAC - https://github.com/Azure/aks-hci/issues/51.  I could previously get past this stage in WAC prior to deploying/uninstalling  the workload cluster via PoSh.  I've restarted the WAC engine / browser and get the same outcome

![image](https://user-images.githubusercontent.com/8145761/97416741-befddc80-18fe-11eb-9cae-3b43055b68a4.png)

**Collect log files**
- From a PowerShell Admin window run **Collect-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

[aggregated-gateway-logs.zip](https://github.com/Azure/aks-hci/files/5451017/aggregated-gateway-logs.zip)

The HCI log files are 57MB - I can provide if required out-of-band

**Comment by abhilashaagarwala** [comment]
@dmc-tech  can I close this bug if it is not repro-ing with the latest release (Feb update)?

**Comment by abhilashaagarwala** [comment]
Closing this bug due to inactivity. Please reopen if this persists in AKS-HCI GA build - https://github.com/Azure/aks-hci/releases/tag/AKS-HCI-2105
