### ISSUE TITLE
Failed to retrieve azure-arc-onboarding pods

### ISSUE THREAD

**Issue by Jerwangsample** [Azure/aks-hci#57]
**Describe the bug**
failed to retrieve  azure-arc-onboarding data

**To Reproduce**
1. create cluster 
2. create a Service Principle 
3. Install-AksHciArcOnboarding -clusterName $clusterName -resourcegroup $resourceGroup -location $location -subscriptionid $subscriptionId -clientid $appId -clientsecret $password -tenantid $tenant
4. kubectl logs job/azure-arc-onboarding -n azure-arc-onboarding --follow

**Expected behavior**
it show ARC related the pods.

**Screenshots**
- Successfully retrieved cluster information.
addon.msft.microsoft/arc-onboarding-arctestwcluster created
 - Arc Onboarding Agent has been installed to the cluster
 - To watch progress for the Arc Agents Onboarding run: kubectl logs job/azure-arc-onboarding -n azure-arc-onboarding --follow
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
PS C:\E2EWorkload>  kubectl logs job/azure-arc-onboarding -n azure-arc-onboarding --follow
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
PS C:\E2EWorkload>

**Environment (please complete the following information):**
Name                           Value
----                           -----
cloudConfigLocation            c:\clusterstorage\volume1\Config
controlplaneVmSize             Standard_K8S3_v1
deploymentType                 MultiNode
vnetType                       Transparent
skipUpdates                    False
vlanID                         0
nodeConfigLocation             C:\programdata\wssdagent
nodeAgentPort                  45000
clusterRoleName                ca-4f04d38a-4490-48ef-89b6-4032f7ca790e
wssdImageDir                   c:\clusterstorage\volume1\Images
vnetName                       extSwitch
stagingShare                   http://netapplinux.guest.corp.microsoft.com/AzureEdge
vippoolStartIP
forceDnsReplication            False
loadBalancerVmSize             Standard_K8S_v1
useStagingShare                False
nodeAgentAuthorizerPort        45001
skipHostLimitChecks            False
useStagingCR                   False
macPoolEnd
cloudServiceCidr
sshPublicKey                   C:\Users\wolfpack\.ssh\id_rsa.pub
akshciVersion                  0.9.4.4
insecure                       False
vippoolEndIP
wssdDir                        C:\wssd
macPoolStart

cluster version: 
Version         : v1.18.8

**Comment by zawachte-msft** [comment]
You need to do ...
```ps
Get-AksHciCredential -clusterName $clusterName
```

Before attempting to view these logs. Need to add this to the script output. thanks.
