### ISSUE TITLE
error: the server doesn't have a resource type "job" & "deployments"

### ISSUE THREAD

**Issue by Jerwangsample** [Azure/aks-hci#58]
**Describe the bug**
I created cluster and try to contact to ARC though my Azure subscription. after I run Install-AksHciArcOnboarding command, it says "Arc Onboarding Agent has been installed to the cluster". 
However, if I try to check the deployments, pods, I got the error - " the server doesn't have a resource type "deployments"

I checked that the service principle was created successfully from Azure portal. 

**Environment (please complete the following information):**
OS      Versions
--      --------
Linux   {v1.17.11, v1.18.8, v1.16.10}
Windows {v1.18.8}

command line: 
PS C:\Users\wolfpack> $servicePrinciple = az ad sp create-for-RBAC --name "azure-arc-for-k8s" --scope /subscriptions/$subscriptionId/resourceGroups/$resourceGroup
Changing "azure-arc-for-k8s" to a valid URI of "http://azure-arc-for-k8s", which is the required format used for service principal names
Found an existing application instance of "087ed6e3-e91e-485d-9f75-04645db3264f". We will patch it
Creating a role assignment under the scope of "/subscriptions/5bc38b0f-3105-4d74-8024-a6ee5fd3a211/resourceGroups/AzureArcTest"
  Role assignment already exists.

PS C:\Users\wolfpack> $appId = ($servicePrinciple | ConvertFrom-Json).appId
PS C:\Users\wolfpack> $password = ($servicePrinciple | ConvertFrom-Json).password
PS C:\Users\wolfpack> $tenant = ($servicePrinciple | ConvertFrom-Json).tenant

PS C:\Users\wolfpack> Get-AksHciCluster -clusterName $clusterName

[11/12/2020 07:17:45] Check for 'AksHci' module updates
 - Refreshing repository credentials.
 - Installed module version is 0.2.9
 - Latest module version is 0.2.9
 - You are already up to date
[11/12/2020 07:17:49] Checking for configuration
[11/12/2020 07:17:49] Reading configuration
[11/12/2020 07:17:49] Adjusting configuration
[11/12/2020 07:17:49] Validating configuration
[11/12/2020 07:17:49] Confirming Configuration
[11/12/2020 07:17:49] Determining deployment type
 - This is a multi-node deployment using failover cluster: jMxKfTQyzpnW
[11/12/2020 07:17:49] Retrieving configuration for workload cluster 'samplecluster'
 - Successfully retrieved cluster information.
Name            : samplecluster
Version         : v1.18.8
Control Planes  : 1
Linux Workers   : 1
Windows Workers : 0
Phase           : provisioned
Ready           : True
PS C:\Users\wolfpack> Install-AksHciArcOnboarding -clusterName $clusterName -resourcegroup $resourceGroup -location $location -subscriptionid $subscriptionId -clientid $appId -clientsecret $password -tenantid $tenant
[11/12/2020 07:17:56] Check for 'AksHci' module updates
 - Refreshing repository credentials.
 - Installed module version is 0.2.9
 - Latest module version is 0.2.9
 - You are already up to date
[11/12/2020 07:17:56] Checking for configuration
[11/12/2020 07:17:56] Reading configuration
[11/12/2020 07:17:56] Adjusting configuration
[11/12/2020 07:17:56] Validating configuration
[11/12/2020 07:17:56] Confirming Configuration
[11/12/2020 07:17:56] Determining deployment type
 - This is a multi-node deployment using failover cluster: jMxKfTQyzpnW
[11/12/2020 07:17:56] Retrieving configuration for workload cluster 'samplecluster'
 - Successfully retrieved cluster information.
addon.msft.microsoft/arc-onboarding-samplecluster created
 - Arc Onboarding Agent has been installed to the cluster
 - To watch progress for the Arc Agents Onboarding run: kubectl logs job/azure-arc-onboarding -n azure-arc-onboarding --follow
PS C:\Users\wolfpack> kubectl logs job/azure-arc-onboarding -n azure-arc-onboarding --follow
error: the server doesn't have a resource type "job"
PS C:\Users\wolfpack> kubectl -n azure-arc get deployments,pods
error: the server doesn't have a resource type "deployments"
PS C:\Users\wolfpack>

**Comment by dineshgovindasamy** [comment]
can you please do get-akshcicredential - clustername "targetclustername" before u execute kubectl get logs commands?

u can get the cluster name using get-akshcicluster

**Comment by abhilashaagarwala** [comment]
@Jerwangsample Can you let us know if this bug has been resolved with the Feb release?

**Comment by Jerwangsample** [comment]
no repro anymore.
