### ISSUE TITLE
[BUG] Incorrect PSRemoting detection -december release

### ISSUE THREAD

**Issue by jaromirk** [Azure/aks-hci#64]
**Describe the bug**
When setting AksHciConfig, it fails to determine correctly if PSRemoting is enabled and it fails few moments after.

**To Reproduce**
WSLab scenario fails here: https://github.com/microsoft/WSLab/blob/dev/Scenarios/AzSHCI%20and%20Kubernetes/Scenario.ps1#L130-L132

**Screenshots**
![image](https://user-images.githubusercontent.com/9829838/100940363-17c12600-34f8-11eb-8b54-e646fc5f3ffa.png)

**Comment by jaromirk** [comment]
Well it looks like this script needs now credssp (doublehop).

**Comment by madhanrm** [comment]
Also please note the change in param name in december release
wssdDir -> workingDir
wssdImageDir -> imageDir
-deploymentType is not required

**Comment by jaromirk** [comment]
Thank you! If you see more issues in code (or ideas), please let me know. I'll update wslab scenario tonight. (9AM here)
