### ISSUE TITLE
iSCSI client support in Azure Stack HCI Worker nodes

### ISSUE THREAD

**Issue by Mohkam** [Azure/aks-hci#65]
**Title**: iSCSI client in HCI AKS Linux Worker nodes
**Description**: 
When trying to deploy OpenEBS as storage solution for my HCI AKS cluster, I found that Linux worker nodes do not support / contain iSCSI clients. Which is pretty basic requirement for any node which is going to deal with storage. 
Having iSCSI clients would enable AKS cluster to utilize iSCSI based storages.

**Comment by SubodhBhargava** [comment]
This was added to AKS-HCI Apr 2021 release (RC build)
