### ISSUE TITLE
[BUG] Get-AksHciCluster error,

### ISSUE THREAD

**Issue by dmc-tech** [Azure/aks-hci#66]
**Describe the bug**
On a cluster deployed using the December 2020 preview bits via WAC, when running Get-AksHciCluster on a HCI node g throws an error that c:\wssd\0.9.4.4\kubeconfig-clustergroup-management cannot be found.

**To Reproduce**
1. On the HCI Node that the AKS HCI deployment was performed, run get-akshciclusters
2. Error is produced:

> C:\Program Files\AksHci\kubectl.exe --kubeconfig=C:\wssd\0.9.4.4\kubeconfig-clustergroup-management get akshciclusters -o json failed to execute [error:
> CreateFile C:\wssd\0.9.4.4\kubeconfig-clustergroup-management: The system cannot find the file specified.]
> At C:\Program Files\WindowsPowerShell\Modules\akshci\0.2.12\Common.psm1:1166 char:9
> +         throw "$command $arguments failed to execute [$err]"
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (C:\Program File...ile specified.]:String) [], RuntimeException
>     + FullyQualifiedErrorId : C:\Program Files\AksHci\kubectl.exe --kubeconfig=C:\wssd\0.9.4.4\kubeconfig-clustergroup-management get akshciclusters -o json fai
>    led to execute [error: CreateFile C:\wssd\0.9.4.4\kubeconfig-clustergroup-management: The system cannot find the file specified.]

**Expected behavior**
A list of the AKS Clusters is returned.

To fix this immediate issue, I copied C:\ClusterStorage\Volume01\AksHCI\kubeconfig-mgmt to C:\wssd\0.9.4.4\kubeconfig-clustergroup-management and it worked as expected.

**Environment (please complete the following information):**
- OS: AzS HCI
- Browser N/A
- Version 0.2.12
- AKS-HCI Version: Public Preview December-2020
- Kubernetes Version: 1.18.8

**Additional context**

**Collect log files**
- From a PowerShell Admin window run **Get-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by mattatmsft** [comment]
Hi Danny - 

Was this a clean install on a fresh set of servers?  The path looks old to me and I'm wondering if it picked up a previous install.  Also, can you verify the WAC Extension version for me please?  This will be in the Installed Extensions list, and my expectation is version 0.420.0.

**Comment by dmc-tech** [comment]
Matt - I haven't re-deployed my HCI cluster.  I removed the previous AKS clusters and added the new PoSh modules to those hosts. WAC version is 0.420.0

**Comment by abhilashaagarwala** [comment]
Hey @dmc-tech! Can you try running Set-AksHciConfig after you finish deploying on WAC and before you run Get-AksHciCluster on PowerShell? Do let me know if that fixed the issue for you!

**Comment by abhilashaagarwala** [comment]
@dmc-tech Can you explain how you removed the previous AKS clusters? I think it may not have been a clean uninstall.

**Comment by abhilashaagarwala** [comment]
@dmc-tech can I close this bug if it is not repro-ing with the latest release (Feb update)?

**Comment by abhilashaagarwala** [comment]
Closing this bug due to inactivity. Please reopen if this persists in AKS-HCI GA build - https://github.com/Azure/aks-hci/releases/tag/AKS-HCI-2105
