### ISSUE TITLE
If I set VLAN to AKsHCI config. New-AKSHCICluster command does not attach the created VM to specified vLAN.

### ISSUE THREAD

**Issue by Mohkam** [Azure/aks-hci#68]
If I set VLAN to AKsHCI config. New-AKSHCICluster command does not attach the created VM to specified vLAN.

Set-AksHciConfig -deploymentType SingleNode -wssdImageDir "E:\RRHCIAKSCA11\Images\" -cloudConfigLocation "E:\RRHCIAKSCA11\Config\" -vnetName External -clusterRoleName RRHCIAKSCA11  -cloudServiceCidr 10.10.120.111/24 -workingDir "E:\RRHCIAKSCA11\WorkingDir\" -imageDir "E:\RRHCIAKSCA11\imageDir\" -vlandID 192 

Hence setup fails unless you manually attach it to desired VLAN.

**Comment by Elektronenvolt** [comment]
There was a typo in docs, I was falling into it too (copy / pasted the parameter from the setup docs) . -vlan**d**ID instead of -vlanID. With -vlanID it will work.

**Comment by mkostersitz** [comment]
This has been fixed in the February release. Please note that the deployment with vLan has changed significantly in the February release. Make sure to follow the updated documentation.
