### ISSUE TITLE
[BUG] Unable to add AKS Extensions nuget pkg in WindowsAdminCenter.  The Operation is "In-Progress" forever.

### ISSUE THREAD

**Issue by sasiezilmadhavan** [Azure/aks-hci#69]
**Describe the bug**
Followed the https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/README.md guide to setup the Azure Stack HCI cluster in Azure. 
Now trying to deploy AKS in this HCI Cluster following the https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/README.md [Installing the Azure Kubernetes Service extension].

Adding the feed to the downloaded nuget package "C:\Users\labadmin\Desktop\msft.sme.aks.0.420.0.nupkg" is keep running for ever.

**To Reproduce**

**Expected behavior**
The AKS Extension should be installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/19148777/105203430-1b247580-5b69-11eb-96e3-373a49632675.png)

**Environment (please complete the following information):**
- OS: Windows Admin Center is running in Windows 10 
- Browser : chrome
- Version 87.0.4280.141
- AKS-HCI Version " : Public Preview Dec-2020

**Additional context**
HCI Cluster is successfully deployed in Azure and registered to Azure.  Any help to install AKS will be helpful.

**Collect log files**
- From a PowerShell Admin window run **Get-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by mattatmsft** [comment]
Instead of taking the full path including the nuget package, can you set the feed location to "C:\Users\labadmin\Desktop" and then click OK.  After that you should just have to wait a second for that to index, and then you'll be able to go to the "Available Extensions" tab and install it from there.

**Comment by sasiezilmadhavan** [comment]
It worked! thank you.
