### ISSUE TITLE
Support AKS Engine on Azure Stack HCI

### ISSUE THREAD

**Issue by msftkenneth** [Azure/aks-hci#70]
As AKS is still under preview on Azure Stack HCI, we would like to leverage AKS Engine to provision Kubernetes cluster on Azure Stack HCI.

It would be preferred as the current AKS deployment does not provide multiple master nodes which to achieve a higher level of resiliency.

**Comment by BenjaminArmstrong** [comment]
@msftkenneth - we do allow you to specify multiple master nodes while deploying a Kubernetes cluster.  I will close this request - but please reach out to me on email if there is more detail here.
