### ISSUE TITLE
Could not retrieve SSH key on step 8.

### ISSUE THREAD

**Issue by JimLin-Qcttw** [Azure/aks-hci#75]
**Describe the bug**
Could not retrieve SSH key.
![image](https://user-images.githubusercontent.com/28556452/108672613-61307880-751d-11eb-82cd-d49b0512deed.png)

the extension check file on the path "C:\ClusterStorage\aks\.ssh\akshci_rsa.pub'"
but, the actually path is "C:\ClusterStorage\aks\AksHCI\.ssh\akshci_rsa.pub"

**To Reproduce**
1. Go to Dashboard of WAC.
2. Click on Create new of "Kubernetes cluster (preview".
3. Finish deployment.
4. See error.

**Expected behavior**
show the ssh key.

**Screenshots**
![image](https://user-images.githubusercontent.com/28556452/108675068-3e07c800-7521-11eb-9521-8fb03c1d3914.png)

**Environment (please complete the following information):**
- OS: Windows Server 2019
- Browser Chrome
- Version 88
- AKS-HCI Version AKS-HCI-Public-Preview-Feb-2021
- Kubernetes Version 1.18.10

**Additional context**
N/A

**Collect log files**
- From a PowerShell Admin window run **Get-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by BenjaminArmstrong** [comment]
@JimLin-Qcttw - Can you check what the version number of the Windows Admin Center Azure Kubernetes Service extension is?  It should be 0.507.0

**Comment by JimLin-Qcttw** [comment]
Yes, the version is 0.507.0 of the Windows Admin Center Azure Kubernetes Service extension.

**Comment by BenjaminArmstrong** [comment]
@mattatmsft - Can you take a look at this?

**Comment by mattatmsft** [comment]
Got it, this will be handled in the next release.

Thank you @JimLin-Qcttw
