### ISSUE TITLE
[BUG] WAC 2103 / AKS extension 0.507.0 / Setup cluster failed with errors when specifying the CloudAgentIP

### ISSUE THREAD

**Issue by dmc-tech** [Azure/aks-hci#78]
**Describe the bug**

**To Reproduce**
1. Go to HCI Cluster
2. click on AKS Extension 
3. When entering the steps for Host Configuration, specify a static IP for the Cloud Agent IP and static IP details for the host and VIP's
4. on step 5, Review + create, go ahead and create.  After a few minutes, see the error:

Failed with errors
Duration: 1 minutes 20 seconds
Cannot process argument transformation on parameter 'IpAddressStr'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Net.IPAddress".

Cannot process argument transformation on parameter 'IpAddress1'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Net.IPAddress".

Cannot process argument transformation on parameter 'IpAddressStr'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Net.IPAddress".

Cannot process argument transformation on parameter 'IpAddress1'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Net.IPAddress".

The Cloud Agent generic service is created on the cluster without IP address, and so needs deleting if re-attempting an install

Leaving the CloudAgentIP blank (I have DHCP in the environment) allows me to proceed past this stage

**Expected behavior**
The cluster is deployed using the Static IP configured for the cloud agent

**Environment (please complete the following information):**
- OS: WIndows 10
- Browser: Edge
- Version Latest
- AKS-HCI Version : Latest
- Kubernetes Version i.e. 1.18.8

**Collect log files**
- From a PowerShell Admin window run **Get-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”
[aggregated-gateway-logs (2).txt](https://github.com/Azure/aks-hci/files/6084394/aggregated-gateway-logs.2.txt)

**Comment by dineshgovindasamy** [comment]
@mattatmsft Can you please take a look?

**Comment by mattatmsft** [comment]
Yep!  @dmc-tech you're correct.   In this scenario the easiest way around this is to leave CloudAgentIp blank, or you can provide a CIDR.  We have this bug fixed in the upcoming release.
