### ISSUE TITLE
[BUG] Kubernetes Scheduling of Linux Helm Charts to Windows Nodes 

### ISSUE THREAD

**Issue by penorouzi** [Azure/aks-hci#83]
**Describe the bug**

When I try to install a Linux Helm chart that doesn't specify nodeSelector, some of its pods get scheduled onto my windows node which causes deployment issues. For example Helm chart installation of [Kubeapps](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps) fails because some of applications pods get scheduled on my cluster's Windows. 

**To Reproduce**

Try to install [Kubeapps](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps) on a ASK HCI cluster with one Windows worker node. Kubernetes schedules some of the pods to the Windows worker node which causes issues with running the pods. 

**Expected behavior**

Based on my conversation with Subodh, even though there is no clear definition of nodeSelector in the deployment file, all pods should get scheduled onto my available Linux worker nodes and no pod should get scheduled on Windows worker nodes.

**Screenshots**

**Environment (please complete the following information):**
- OS: [e.g. iOS] Windows Server 2019
- AKS-HCI Version (i.e. Public Preview October-2020) : 0.9.7.1
- Kubernetes Version (i.e. 1.18.8) : 1.18.14 (Deployed on Azure VM and the cluster has 1 Linux worker node, 1 Windows worker node)

**Comment by abhilashaagarwala** [comment]
Doc item opened to cover using taints and tolerations in order to deploy applications on the right nodes when using helm charts.

**Comment by abhilashaagarwala** [comment]
Docs added here - https://docs.microsoft.com/en-us/azure-stack/aks-hci/adapt-apps-mixed-os-clusters#taints-and-tolerations

**Comment by abhilashaagarwala** [comment]
@penorouzi - Lmk if the docs above answer your questions!
