### ISSUE TITLE
[BUG] Clarifying storage needs on C drive for Set-AksHciConfig

### ISSUE THREAD

**Issue by polarapfel** [Azure/aks-hci#85]
**Describe the bug**

The storage requirements on C drive are not clear. When running Set-AksHciConfig as such:

```
Set-AksHciConfig -vnet $vnet -imageDir "N:\AKS-HCI\Images" -cloudConfigLocation "N:\AKS-HCI\Config" -nodeConfigLocation "N:\AKS-HCI/" -enableDiagnosticData -Verbose
```

... renders this:

```
Not enough disk space is available on drive 'C:'.
At C:\Program Files\WindowsPowerShell\Modules\Moc\0.2.25\Common.psm1:2046 char:13
+             throw $("Not enough disk space is available on drive '$dr ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Not enough disk... on drive 'C:'.:String) [], RuntimeException
    + FullyQualifiedErrorId : Not enough disk space is available on drive 'C:'.
```

My expectation was using all options pointing to another drive, the footprint on C drive would not be a problem. At the very least, required free space on C should be documented, as well as how C drive storage is consumed further on.

**To Reproduce**

Run Set-AksHciConfig with little space left on C drive.

**Expected behavior**

When setting imageDir, cloudConfigLocation and nodeConfigLocation to a drive different than C, storage on C drive should not be a concern.

**Screenshots**

Not applicable.

**Environment (please complete the following information):**

```
(Get-WmiObject Win32_OperatingSystem).Version
10.0.17763
(Get-WmiObject Win32_OperatingSystem).Caption
Microsoft Windows Server 2019 Datacenter
```

**Additional context**

None.

**Collect log files**

None available (before Set-AksHciConfig).

**Comment by madhanrm** [comment]
Can you please try the latest GA build?

**Comment by madhanrm** [comment]
Can you also pass -workingDir as N:\<somedir>

Can you also do get-akshciconfig | ConvertTo-Json -Depth 10

**Comment by mkostersitz** [comment]
@polarapfel  Please let us know if the above command line change resolved the issue

**Comment by abhilashaagarwala** [comment]
Closing bug due to no response. please reopen if the above solution does not work.
