### ISSUE TITLE
[BUG] Management cluster VM is constantly above 100% memory pressure

### ISSUE THREAD

**Issue by infbase** [Azure/aks-hci#88]
**Describe the bug**
Management cluster VM is constantly above 100% memory pressure. Perhaps a different memory configuration should be used?

**To Reproduce**
1. Deploy AKS service on an HCI cluster

**Expected behavior**
Memory pressure should be under 100%

**Screenshots**
![image](https://user-images.githubusercontent.com/7604619/114317718-577cc780-9b01-11eb-9bd8-0f89b0699414.png)

![image](https://user-images.githubusercontent.com/7604619/114317566-978f7a80-9b00-11eb-86e2-2a42e8e96a85.png)

![image](https://user-images.githubusercontent.com/7604619/114317574-a24a0f80-9b00-11eb-86f0-f0d91b72f38d.png)

**Environment (please complete the following information):**
- AKS-HCI Version 0.9.7.3
- Kubernetes Version 1.18.14

**Collect log files**
https://1drv.ms/u/s!Aq86yCB_tZaGoZYFq72eJBf6r2oLHg?e=Dw3kPK

**Comment by msjingli** [comment]
Actually this is not related with performance and it can be safely ignored. We have document it here, https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues#hyper-v-manager-shows-high-cpu-andor-memory-demands-for-the-management-cluster
