### ISSUE TITLE
[BUG] Azure Arc pods cannot be scheduled on Windows only cluster

### ISSUE THREAD

**Issue by infbase** [Azure/aks-hci#89]
**Describe the bug**
If a cluster does not have Linux worker nodes, Azure Arc pods cannot be scheduled.

**To Reproduce**
Create a new cluster with Azure Arc integration enabled and only Windows worker nodes.

**Expected behavior**
Pre-creation validation should not allow a cluster to be created with Azure Arc integration enabled and no Linux worker nodes.

**Screenshots**
![image](https://user-images.githubusercontent.com/7604619/114334459-823b4000-9b42-11eb-9a3a-0ffa3aaf1068.png)

**Environment (please complete the following information):**
- AKS-HCI Version 0.9.7.3
- Kubernetes Version 1.18.14

**Comment by abhilashaagarwala** [comment]
You need atleast 1 linux node in your AKS-HCI cluster to connect it to Azure Arc. Please take a look at this section for pre-requisites - https://docs.microsoft.com/en-us/azure-stack/aks-hci/connect-to-arc#before-you-begin

**Comment by abhilashaagarwala** [comment]
This is a known issue and has been documented here - https://docs.microsoft.com/en-us/azure-stack/aks-hci/connect-to-arc. In the meantime, we're investigating the ability to schedule Arc pods on control plane nodes.

**Comment by abhilashaagarwala** [comment]
Closing this bug as I have opened an enhancement - https://github.com/Azure/aks-hci/issues/102
