### ISSUE TITLE
[BUG] Connecting Kubernetes cluster to Arc never complete in Windows Admin Center Create Kubernetes cluster wizard

### ISSUE THREAD

**Issue by squasta** [Azure/aks-hci#92]
I followed the setup guide (https://github.com/Azure/aks-hci/blob/main/eval/steps/2a_DeployAKSHCI_WAC.md) to create a new kubernetes cluster (the management cluster is running and already registered as an Arc Kubernetes cluster). The host is an Azure VM

Installation of kubernetes cluster (for workloads) never finished, still got the message We are creating the Kubernetes Cluster, Connecting cluster to Arc... duration now is more than 1 hour 35 minutes...

I think I forgot to specify additional node pool. So there is only a master node pool (I can see 2 VM in hyper-V manager : one for the load balancer, one for the master)

I tried to deploy a second Kubernetes cluster with a worker node pool (3 nodes), I got a Failed with errors (cannot index into a null array) during Connecting cluster to Azure Arc phase

**Comment by arfongmsft** [comment]
Hi Stanislas, 

You're correct that at least 1 additional Linux node pool is needed to successfully deploy target clusters that are connected to Azure Arc. 

With regards to the error you're seeing when you retried: "(cannot index into a null array) during Connecting cluster to Azure Arc phase," this is a known issue that we've documented for this release. When you see this message, the target cluster deployment and connection to Azure Arc have actually completed successfully, but this is an error that appears in WAC after the Azure Arc setup completes, so if you navigate back to the dashboard, you shouldn't have any issues with your clusters. This bug will be fixed for GA!

Thanks,
Ariel

**Comment by abhilashaagarwala** [comment]
@squasta - Have you been able to check if you're clusters are Arc connected?

**Comment by abhilashaagarwala** [comment]
Closing this bug due to inactivity. Please reopen if you see this in the GA build of AKS-HCI - https://github.com/Azure/aks-hci/releases/tag/AKS-HCI-2105
