### ISSUE TITLE
[BUG] Install-AksHci - .wssd\cloudconfig -  it does not exist.

### ISSUE THREAD

**Issue by aszykm** [Azure/aks-hci#93]
Hello,

I would like to deploy Azure Kubernetes Service on my Azure Stack HCI.

When I set all parameters and run _Install-AksHCI_ than I got error like this:

Copy-Item : Cannot find path 'C:\Users\Administrator.ASZYK\.wssd\cloudconfig' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\Moc\0.2.25\Common.psm1:1537 char:5
+     Copy-Item -Path $source -Destination $remotePath
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Admini...ssd\cloudconfig:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Failed to start service 'WSSD Agent Service (wssdagent)'.
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
    + PSComputerName        : hp-ms-01

Failed to start service 'WSSD Agent Service (wssdagent)'.
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
    + PSComputerName        : hp-ms-03

The problem causes a lot of other errors.

Did you have the same or similar problems?

Regards,
Mateusz.

**Comment by abhilashaagarwala** [comment]
Hey @aszykm - We have released a new version of AKS-HCI. Can you try installing the new release and let us know if you still face the same issue? https://github.com/Azure/aks-hci/releases/tag/AKS-HCI-2104

**Comment by aszykm** [comment]
Hey @abhilashaagarwala 
Update resolve my problem. 

But in the next steps I got another error:
![image](https://user-images.githubusercontent.com/7985066/119342237-0da50680-bc95-11eb-8ac6-645e29762fe1.png)

**Comment by madhanrm** [comment]
@aszykm , you are on 0.9.8.10427.
GA is 1.0.0.10517

**Comment by abhilashaagarwala** [comment]
Can you try this on the AKS-HCI GA release and let us know if it persists? https://github.com/Azure/aks-hci/releases/tag/AKS-HCI-2105

**Comment by aszykm** [comment]
Hello,

The same error :(
![image](https://user-images.githubusercontent.com/7985066/121824192-95859b80-ccaa-11eb-9fc7-85cbda88a5ae.png)

**Comment by aszykm** [comment]
I run manually mocctl.exe and I did not get an error. Again I ran with verbose option and I received the code: AlreadyExist:
![image](https://user-images.githubusercontent.com/7985066/121824379-2610ab80-ccac-11eb-9c0d-bae945e16247.png)

**Comment by mkostersitz** [comment]
@aszykm  could you please provide a fresh set of logs from Get-AksHciLogs and let @madhanrm know so we can take a look

**Comment by aszykm** [comment]
These are two servers for the development environment each with one SSD. 

Is it possible to increase timeout?

**Comment by madhanrm** [comment]
Can we close this bug and open a separate bug to investigate that please?

**Comment by aszykm** [comment]
> Can we close this bug and open a separate bug to investigate that please?

Could you answer the question then we can close the issue?
How I can increase the timeout ?

**Comment by madhanrm** [comment]
We have removed the timeout in Aug release. Can you try the latest release.

**Comment by madhanrm** [comment]
Can we close this bug if this is resolved.

Also if you have SSD and the copy is taking more than 10 minutes, there is some issue. Can you manually try to copy the VHD and see if it performs well.

**Comment by abhilashaagarwala** [comment]
Closing this bug due to inactivity and its now a year old.
