### ISSUE TITLE
[BUG] Applying platform configuration fails when proxy blocks older user-agent strings

### ISSUE THREAD

**Issue by eponerine** [Azure/aks-hci#95]
**Describe the bug**
Since the CDN is still being delivered over HTTP (not HTTPS), some environments may have an HTTP Proxy (like ZScaler) in place to filter traffic. One of those filters is blocking old user-agent strings. It appears that when applying platform configuration, the mocked user-agent string is "Google Chrome 65", which is so old that some services outright block HTTP requests originating from it. If possible, can we update this to something new (like Google Chrome 90?) so that this step doesn't bomb out?

**To Reproduce**
1. Configure ZScaler to block out-of-date user-agent strings
2. Configure AKS-on-HCI thru WAC (or even PowerShell?)
3. Attempt to apply platform config
4. Fail (see screenshot)

**Expected behavior**
The process not blowing up due to such an out-of-date user-agent string

**Screenshots**
![image](https://user-images.githubusercontent.com/503974/118860809-d0fa9900-b8a9-11eb-827e-0807937ffb66.png)

**Environment (please complete the following information):**
- OS: n/a
- Browser: n/a really
- Version: n/a
- AKS-HCI Version: Public Preview April-2021
- Kubernetes Version: n/a

**Additional context**
Using WAC 2103.2, build 1.3.2104.20002

**Collect log files**
- Will provide logs by request

**Comment by dineshgovindasamy** [comment]
@nwoodmsft Can you please take a look?

**Comment by nwoodmsft** [comment]
The user-agent is updated to Chrome 91 and the change should be present in the July release.
